from . import array as array, local as local


def log_debug(arg: str, /) -> None: ...

def log_error(arg: str, /) -> None: ...

def log_info(arg: str, /) -> None: ...

def log_warn(arg: str, /) -> None: ...
