# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/rmf_traffic_msgs/msg/negotiation_participant_ack.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQmake87_messages_ros2/jazzy/rmf_traffic_msgs/msg/negotiation_participant_ack.proto\x12/make87_messages_ros2.jazzy.rmf_traffic_msgs.msg\"]\n\x19NegotiationParticipantAck\x12\x13\n\x0bparticipant\x18\x01 \x01(\x04\x12\x10\n\x08updating\x18\x02 \x01(\x08\x12\x19\n\x11itinerary_version\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.rmf_traffic_msgs.msg.negotiation_participant_ack_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NEGOTIATIONPARTICIPANTACK']._serialized_start=134
  _globals['_NEGOTIATIONPARTICIPANTACK']._serialized_end=227
# @@protoc_insertion_point(module_scope)
