from setuptools import setup, find_packages

setup(
    name="extractor_wrapper",
    version="0.1.1",
    author="Florian BARRE",
    author_email="florian.barre78@gmail.com",
    description="",
    long_description=open("./ReadMe.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/Florian-BARRE/ExtractorWrapper",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
    install_requires=[
        "beautifulsoup4",
        "cffi",
        "colorama",
        "colorclass",
        "compressed-rtf",
        "contourpy",
        "cryptography",
        "cycler",
        "easygui",
        "ebcdic",
        "et_xmlfile",
        "extract-msg",
        "fonttools",
        "kiwisolver",
        "lark",
        "loggerplusplus",
        "lxml",
        "matplotlib",
        "msoffcrypto-tool",
        "numpy",
        "olefile",
        "oletools",
        "openpyxl",
        "packaging",
        "pandas",
        "pcodedmp",
        "pillow",
        "pycparser",
        "pyparsing",
        "PyPDF2",
        "python-dateutil",
        "python-docx",
        "pytz",
        "red-black-tree-mod",
        "RTFDE",
        "six",
        "soupsieve",
        "typing_extensions",
        "tzdata",
        "tzlocal",
        "win_unicode_console"
    ],
    include_package_data=True,
)