# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/marti_introspection_msgs/msg/node_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.marti_introspection_msgs.msg import param_info_pb2 as make87__messages__ros2_dot_jazzy_dot_marti__introspection__msgs_dot_msg_dot_param__info__pb2
from make87_messages_ros2.jazzy.marti_introspection_msgs.msg import service_info_pb2 as make87__messages__ros2_dot_jazzy_dot_marti__introspection__msgs_dot_msg_dot_service__info__pb2
from make87_messages_ros2.jazzy.marti_introspection_msgs.msg import topic_info_pb2 as make87__messages__ros2_dot_jazzy_dot_marti__introspection__msgs_dot_msg_dot_topic__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGmake87_messages_ros2/jazzy/marti_introspection_msgs/msg/node_info.proto\x12\x37make87_messages_ros2.jazzy.marti_introspection_msgs.msg\x1aHmake87_messages_ros2/jazzy/marti_introspection_msgs/msg/param_info.proto\x1aJmake87_messages_ros2/jazzy/marti_introspection_msgs/msg/service_info.proto\x1aHmake87_messages_ros2/jazzy/marti_introspection_msgs/msg/topic_info.proto\"\xdc\x02\n\x08NodeInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x17\n\x0fnodelet_manager\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12R\n\x06topics\x18\x05 \x03(\x0b\x32\x42.make87_messages_ros2.jazzy.marti_introspection_msgs.msg.TopicInfo\x12V\n\nparameters\x18\x06 \x03(\x0b\x32\x42.make87_messages_ros2.jazzy.marti_introspection_msgs.msg.ParamInfo\x12V\n\x08services\x18\x07 \x03(\x0b\x32\x44.make87_messages_ros2.jazzy.marti_introspection_msgs.msg.ServiceInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.marti_introspection_msgs.msg.node_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_NODEINFO']._serialized_start=357
  _globals['_NODEINFO']._serialized_end=705
# @@protoc_insertion_point(module_scope)
