# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/psdk_interfaces/srv/camera_shoot_burst_photo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNmake87_messages_ros2/humble/psdk_interfaces/srv/camera_shoot_burst_photo.proto\x12/make87_messages_ros2.humble.psdk_interfaces.srv\x1a!make87_messages/core/header.proto\"~\n\x1c\x43\x61meraShootBurstPhotoRequest\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x15\n\rpayload_index\x18\x02 \x01(\r\x12\x19\n\x11photo_burst_count\x18\x03 \x01(\r\"^\n\x1d\x43\x61meraShootBurstPhotoResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x0f\n\x07success\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.psdk_interfaces.srv.camera_shoot_burst_photo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERASHOOTBURSTPHOTOREQUEST']._serialized_start=166
  _globals['_CAMERASHOOTBURSTPHOTOREQUEST']._serialized_end=292
  _globals['_CAMERASHOOTBURSTPHOTORESPONSE']._serialized_start=294
  _globals['_CAMERASHOOTBURSTPHOTORESPONSE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
