def getDefaultCachePath() -> str: ...
def getDefaultModelsPath() -> str: ...
def getDownloadEndpoint() -> str: ...
def getHealthEndpoint() -> str: ...
def setDefaultCachePath(path: str) -> None: ...
def setDefaultModelsPath(path: str) -> None: ...
def setDownloadEndpoint(endpoint: str) -> None: ...
def setHealthEndpoint(endpoint: str) -> None: ...
