import gradio as gr
from ..data_models import Note as Note, PianoRollData as PianoRollData, clean_piano_roll_data as clean_piano_roll_data
from ..timing_utils import generate_note_id as generate_note_id

def from_notes(notes: list[tuple[int, float, float]], tempo: int = 120, lyrics: list[str] | None = None) -> PianoRollData: ...
def from_midi_numbers(midi_notes: list[int], durations: list[float] | None = None, start_times: list[float] | None = None, tempo: int = 120) -> PianoRollData: ...
def from_frequencies(frequencies: list[float], durations: list[float] | None = None, start_times: list[float] | None = None, tempo: int = 120) -> PianoRollData: ...
def from_tts_output(text: str, alignment: list[tuple[str, float, float]], f0_data: list[float] | None = None, tempo: int = 120) -> dict: ...
def from_midi_generation(generated_sequence: list[dict], tempo: int = 120) -> dict: ...
def _create_f0_line_data(f0_values: list[float], total_duration: float, tempo: int, pixels_per_beat: int) -> dict: ...
def create_pianoroll_with_data(data: dict, **component_kwargs) -> gr.Blocks: ...
def quick_demo(notes: list[tuple[int, float, float]], title: str = 'Quick Piano Roll Demo', tempo: int = 120, **component_kwargs) -> gr.Blocks: ...
def analyze_notes(piano_roll_data: dict) -> dict: ...
def auto_analyze(model_output_data: list | dict, output_type: str = 'auto') -> dict: ...
