"""Constants for metrics module."""
LEAD_TIME = 'lead_time'
CYCLE_TIME = 'cycle_time'
LIFE_TIME = 'life_time'
ITEMS_COUNT = 'items_count'
FLOW_TIME = 'flow_time'
FLOW_VELOCITY = 'flow_velocity'
FLOW_LOAD = 'flow_load'
FLOW_EFFICIENCY = 'flow_efficiency'
YEAR_MONTH = 'year_month'
CLOSED = 'closed'
OPEN = 'open'
THROUGHPUT = 'throughput'
WIP = 'WIP'
