# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/tuw_object_msgs/srv/get_shape_array.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.rolling.tuw_object_msgs.msg import shape_array_pb2 as make87__messages__ros2_dot_rolling_dot_tuw__object__msgs_dot_msg_dot_shape__array__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/rolling/tuw_object_msgs/srv/get_shape_array.proto\x12\x30make87_messages_ros2.rolling.tuw_object_msgs.srv\x1a\x42make87_messages_ros2/rolling/tuw_object_msgs/msg/shape_array.proto\"\x16\n\x14GetShapeArrayRequest\"e\n\x15GetShapeArrayResponse\x12L\n\x06shapes\x18\x01 \x01(\x0b\x32<.make87_messages_ros2.rolling.tuw_object_msgs.msg.ShapeArrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.tuw_object_msgs.srv.get_shape_array_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSHAPEARRAYREQUEST']._serialized_start=192
  _globals['_GETSHAPEARRAYREQUEST']._serialized_end=214
  _globals['_GETSHAPEARRAYRESPONSE']._serialized_start=216
  _globals['_GETSHAPEARRAYRESPONSE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
