# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/sick_safevisionary_interfaces/msg/general_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQmake87_messages_ros2/jazzy/sick_safevisionary_interfaces/msg/general_status.proto\x12<make87_messages_ros2.jazzy.sick_safevisionary_interfaces.msg\"\x95\x02\n\rGeneralStatus\x12\x17\n\x0frun_mode_active\x18\x01 \x01(\r\x12\x14\n\x0c\x64\x65vice_error\x18\x02 \x01(\r\x12\x19\n\x11\x61pplication_error\x18\x03 \x01(\r\x12\x12\n\nsleep_mode\x18\x04 \x01(\r\x12\x16\n\x0ewait_for_input\x18\x05 \x01(\r\x12\x18\n\x10wait_for_cluster\x18\x06 \x01(\r\x12\x1d\n\x15\x63ontamination_warning\x18\x07 \x01(\r\x12\x1b\n\x13\x63ontamination_error\x18\x08 \x01(\r\x12\x1b\n\x13\x64\x65\x61\x64_zone_detection\x18\t \x01(\r\x12\x1b\n\x13temperature_warning\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.sick_safevisionary_interfaces.msg.general_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GENERALSTATUS']._serialized_start=148
  _globals['_GENERALSTATUS']._serialized_end=425
# @@protoc_insertion_point(module_scope)
