# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/rc_reason_msgs/srv/delete_regions_of_interest3_d.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.rc_common_msgs.msg import return_code_pb2 as make87__messages__ros2_dot_jazzy_dot_rc__common__msgs_dot_msg_dot_return__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQmake87_messages_ros2/jazzy/rc_reason_msgs/srv/delete_regions_of_interest3_d.proto\x12-make87_messages_ros2.jazzy.rc_reason_msgs.srv\x1a?make87_messages_ros2/jazzy/rc_common_msgs/msg/return_code.proto\"B\n DeleteRegionsOfInterest3DRequest\x12\x1e\n\x16region_of_interest_ids\x18\x01 \x03(\t\"s\n!DeleteRegionsOfInterest3DResponse\x12N\n\x0breturn_code\x18\x01 \x01(\x0b\x32\x39.make87_messages_ros2.jazzy.rc_common_msgs.msg.ReturnCodeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.rc_reason_msgs.srv.delete_regions_of_interest3_d_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELETEREGIONSOFINTEREST3DREQUEST']._serialized_start=197
  _globals['_DELETEREGIONSOFINTEREST3DREQUEST']._serialized_end=263
  _globals['_DELETEREGIONSOFINTEREST3DRESPONSE']._serialized_start=265
  _globals['_DELETEREGIONSOFINTEREST3DRESPONSE']._serialized_end=380
# @@protoc_insertion_point(module_scope)
