# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/sbg_driver/msg/sbg_status.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.sbg_driver.msg import sbg_status_aiding_pb2 as make87__messages__ros2_dot_humble_dot_sbg__driver_dot_msg_dot_sbg__status__aiding__pb2
from make87_messages_ros2.humble.sbg_driver.msg import sbg_status_com_pb2 as make87__messages__ros2_dot_humble_dot_sbg__driver_dot_msg_dot_sbg__status__com__pb2
from make87_messages_ros2.humble.sbg_driver.msg import sbg_status_general_pb2 as make87__messages__ros2_dot_humble_dot_sbg__driver_dot_msg_dot_sbg__status__general__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;make87_messages_ros2/humble/sbg_driver/msg/sbg_status.proto\x12*make87_messages_ros2.humble.sbg_driver.msg\x1a!make87_messages/core/header.proto\x1a\x42make87_messages_ros2/humble/sbg_driver/msg/sbg_status_aiding.proto\x1a?make87_messages_ros2/humble/sbg_driver/msg/sbg_status_com.proto\x1a\x43make87_messages_ros2/humble/sbg_driver/msg/sbg_status_general.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\x8c\x03\n\tSbgStatus\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12\x12\n\ntime_stamp\x18\x03 \x01(\r\x12T\n\x0estatus_general\x18\x04 \x01(\x0b\x32<.make87_messages_ros2.humble.sbg_driver.msg.SbgStatusGeneral\x12L\n\nstatus_com\x18\x05 \x01(\x0b\x32\x38.make87_messages_ros2.humble.sbg_driver.msg.SbgStatusCom\x12R\n\rstatus_aiding\x18\x06 \x01(\x0b\x32;.make87_messages_ros2.humble.sbg_driver.msg.SbgStatusAidingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.sbg_driver.msg.sbg_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SBGSTATUS']._serialized_start=400
  _globals['_SBGSTATUS']._serialized_end=796
# @@protoc_insertion_point(module_scope)
