# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/moveit_msgs/srv/check_if_robot_state_exists_in_warehouse.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[make87_messages_ros2/rolling/moveit_msgs/srv/check_if_robot_state_exists_in_warehouse.proto\x12,make87_messages_ros2.rolling.moveit_msgs.srv\"H\n)CheckIfRobotStateExistsInWarehouseRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05robot\x18\x02 \x01(\t\"<\n*CheckIfRobotStateExistsInWarehouseResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.moveit_msgs.srv.check_if_robot_state_exists_in_warehouse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKIFROBOTSTATEEXISTSINWAREHOUSEREQUEST']._serialized_start=141
  _globals['_CHECKIFROBOTSTATEEXISTSINWAREHOUSEREQUEST']._serialized_end=213
  _globals['_CHECKIFROBOTSTATEEXISTSINWAREHOUSERESPONSE']._serialized_start=215
  _globals['_CHECKIFROBOTSTATEEXISTSINWAREHOUSERESPONSE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
