# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/rcl_interfaces/srv/set_logger_levels.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/rcl_interfaces/srv/set_logger_levels.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.rcl_interfaces.msg import logger_level_pb2 as make87__messages__ros2_dot_jazzy_dot_rcl__interfaces_dot_msg_dot_logger__level__pb2
from make87_messages_ros2.jazzy.rcl_interfaces.msg import set_logger_levels_result_pb2 as make87__messages__ros2_dot_jazzy_dot_rcl__interfaces_dot_msg_dot_set__logger__levels__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEmake87_messages_ros2/jazzy/rcl_interfaces/srv/set_logger_levels.proto\x12-make87_messages_ros2.jazzy.rcl_interfaces.srv\x1a@make87_messages_ros2/jazzy/rcl_interfaces/msg/logger_level.proto\x1aLmake87_messages_ros2/jazzy/rcl_interfaces/msg/set_logger_levels_result.proto\"d\n\x16SetLoggerLevelsRequest\x12J\n\x06levels\x18\x01 \x03(\x0b\x32:.make87_messages_ros2.jazzy.rcl_interfaces.msg.LoggerLevel\"p\n\x17SetLoggerLevelsResponse\x12U\n\x07results\x18\x01 \x03(\x0b\x32\x44.make87_messages_ros2.jazzy.rcl_interfaces.msg.SetLoggerLevelsResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.rcl_interfaces.srv.set_logger_levels_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETLOGGERLEVELSREQUEST']._serialized_start=264
  _globals['_SETLOGGERLEVELSREQUEST']._serialized_end=364
  _globals['_SETLOGGERLEVELSRESPONSE']._serialized_start=366
  _globals['_SETLOGGERLEVELSRESPONSE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
