# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bitbucket_pr_field import BitbucketPRField  # noqa: E501
from swagger_client.rest import ApiException


class TestBitbucketPRField(unittest.TestCase):
    """BitbucketPRField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBitbucketPRField(self):
        """Test BitbucketPRField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bitbucket_pr_field.BitbucketPRField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
