# coding: utf-8

"""
    DeviceServer

    DeviceServer API  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import DeviceServer
from DeviceServer.api.serial_mux_api import SerialMuxApi  # noqa: E501
from DeviceServer.rest import ApiException


class TestSerialMuxApi(unittest.TestCase):
    """SerialMuxApi unit test stubs"""

    def setUp(self):
        self.api = DeviceServer.api.serial_mux_api.SerialMuxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_put_serial_test_message(self):
        """Test case for put_serial_test_message

        Serial Message Test  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
