# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/off_highway_premium_radar_sample_msgs/msg/misalignment_packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n_make87_messages_ros2/humble/off_highway_premium_radar_sample_msgs/msg/misalignment_packet.proto\x12\x45make87_messages_ros2.humble.off_highway_premium_radar_sample_msgs.msg\x1a!make87_messages/core/header.proto\"\xf1\x03\n\x12MisalignmentPacket\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\r\n\x05theta\x18\x02 \x01(\x02\x12\x16\n\x0etheta_variance\x18\x03 \x01(\x02\x12\x0b\n\x03phi\x18\x04 \x01(\x02\x12\x14\n\x0cphi_variance\x18\x05 \x01(\x02\x12\x0f\n\x07phi_eme\x18\x06 \x01(\x02\x12\x18\n\x10phi_eme_variance\x18\x07 \x01(\x02\x12\x0e\n\x06status\x18\x08 \x01(\r\x12\x12\n\nstatus_eme\x18\t \x01(\r\x12\x1e\n\x16percent_negative_theta\x18\n \x01(\x02\x12\x15\n\rmin_theta_sos\x18\x0b \x01(\x02\x12\x15\n\rmax_theta_sos\x18\x0c \x01(\x02\x12\x1a\n\x12theta_sos_variance\x18\r \x01(\x02\x12\x16\n\x0etheta_sos_mean\x18\x0e \x01(\x02\x12\x13\n\x0bmin_phi_sos\x18\x0f \x01(\x02\x12\x13\n\x0bmax_phi_sos\x18\x10 \x01(\x02\x12\x18\n\x10phi_sos_variance\x18\x11 \x01(\x02\x12\x14\n\x0cphi_sos_mean\x18\x12 \x01(\x02\x12\x16\n\x0ephi_sos_spread\x18\x13 \x01(\x02\x12\x0f\n\x07num_sos\x18\x14 \x01(\r\x12\x0f\n\x07num_eme\x18\x15 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.off_highway_premium_radar_sample_msgs.msg.misalignment_packet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MISALIGNMENTPACKET']._serialized_start=206
  _globals['_MISALIGNMENTPACKET']._serialized_end=703
# @@protoc_insertion_point(module_scope)
