from lxml.etree import Element as Element
from mrender.md import Markdown as Markdown

def html_to_markdown_with_depth(element: Element, depth: int = 0) -> str: ...
def display_markdown_hierarchically(markdown_text, max_depth) -> None: ...
def cli(path, max_depth) -> None: ...
def extract_links(markdown_content): ...
