# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/ros_gz_interfaces/msg/param_vec.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.rcl_interfaces.msg import parameter_pb2 as make87__messages__ros2_dot_jazzy_dot_rcl__interfaces_dot_msg_dot_parameter__pb2
from make87_messages_ros2.jazzy.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_jazzy_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@make87_messages_ros2/jazzy/ros_gz_interfaces/msg/param_vec.proto\x12\x30make87_messages_ros2.jazzy.ros_gz_interfaces.msg\x1a=make87_messages_ros2/jazzy/rcl_interfaces/msg/parameter.proto\x1a\x34make87_messages_ros2/jazzy/std_msgs/msg/header.proto\"\x95\x01\n\x08ParamVec\x12?\n\x06header\x18\x01 \x01(\x0b\x32/.make87_messages_ros2.jazzy.std_msgs.msg.Header\x12H\n\x06params\x18\x02 \x03(\x0b\x32\x38.make87_messages_ros2.jazzy.rcl_interfaces.msg.Parameterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.ros_gz_interfaces.msg.param_vec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMVEC']._serialized_start=236
  _globals['_PARAMVEC']._serialized_end=385
# @@protoc_insertion_point(module_scope)
