<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
<meta name="generator" content="pdoc3 0.11.6">
<title>piecad.projectbox API documentation</title>
<meta name="description" content="THIS FEATURE IS SOMEWHAT EXPERIMENTAL, THE API SUBJECT TO CHANGE …">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/13.0.0/sanitize.min.css" integrity="sha512-y1dtMcuvtTMJc1yPgEqF0ZjQbhnc/bFhyvIyVNb9Zk5mIGtqVaAB1Ttl28su8AvFMOY0EwRbAe+HCLqj6W7/KA==" crossorigin>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/10up-sanitize.css/13.0.0/typography.min.css" integrity="sha512-Y1DYSb995BAfxobCkKepB1BqJJTPrOp3zPL74AWFugHHmmdcvO+C48WLrUOlhGMc0QG7AE3f7gmvvcrmX2fDoA==" crossorigin>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/default.min.css" crossorigin>
<style>:root{--highlight-color:#fe9}.flex{display:flex !important}body{line-height:1.5em}#content{padding:20px}#sidebar{padding:1.5em;overflow:hidden}#sidebar > *:last-child{margin-bottom:2cm}.http-server-breadcrumbs{font-size:130%;margin:0 0 15px 0}#footer{font-size:.75em;padding:5px 30px;border-top:1px solid #ddd;text-align:right}#footer p{margin:0 0 0 1em;display:inline-block}#footer p:last-child{margin-right:30px}h1,h2,h3,h4,h5{font-weight:300}h1{font-size:2.5em;line-height:1.1em}h2{font-size:1.75em;margin:2em 0 .50em 0}h3{font-size:1.4em;margin:1.6em 0 .7em 0}h4{margin:0;font-size:105%}h1:target,h2:target,h3:target,h4:target,h5:target,h6:target{background:var(--highlight-color);padding:.2em 0}a{color:#058;text-decoration:none;transition:color .2s ease-in-out}a:visited{color:#503}a:hover{color:#b62}.title code{font-weight:bold}h2[id^="header-"]{margin-top:2em}.ident{color:#900;font-weight:bold}pre code{font-size:.8em;line-height:1.4em;padding:1em;display:block}code{background:#f3f3f3;font-family:"DejaVu Sans Mono",monospace;padding:1px 4px;overflow-wrap:break-word}h1 code{background:transparent}pre{border-top:1px solid #ccc;border-bottom:1px solid #ccc;margin:1em 0}#http-server-module-list{display:flex;flex-flow:column}#http-server-module-list div{display:flex}#http-server-module-list dt{min-width:10%}#http-server-module-list p{margin-top:0}.toc ul,#index{list-style-type:none;margin:0;padding:0}#index code{background:transparent}#index h3{border-bottom:1px solid #ddd}#index ul{padding:0}#index h4{margin-top:.6em;font-weight:bold}@media (min-width:200ex){#index .two-column{column-count:2}}@media (min-width:300ex){#index .two-column{column-count:3}}dl{margin-bottom:2em}dl dl:last-child{margin-bottom:4em}dd{margin:0 0 1em 3em}#header-classes + dl > dd{margin-bottom:3em}dd dd{margin-left:2em}dd p{margin:10px 0}.name{background:#eee;font-size:.85em;padding:5px 10px;display:inline-block;min-width:40%}.name:hover{background:#e0e0e0}dt:target .name{background:var(--highlight-color)}.name > span:first-child{white-space:nowrap}.name.class > span:nth-child(2){margin-left:.4em}.inherited{color:#999;border-left:5px solid #eee;padding-left:1em}.inheritance em{font-style:normal;font-weight:bold}.desc h2{font-weight:400;font-size:1.25em}.desc h3{font-size:1em}.desc dt code{background:inherit}.source > summary,.git-link-div{color:#666;text-align:right;font-weight:400;font-size:.8em;text-transform:uppercase}.source summary > *{white-space:nowrap;cursor:pointer}.git-link{color:inherit;margin-left:1em}.source pre{max-height:500px;overflow:auto;margin:0}.source pre code{font-size:12px;overflow:visible;min-width:max-content}.hlist{list-style:none}.hlist li{display:inline}.hlist li:after{content:',\2002'}.hlist li:last-child:after{content:none}.hlist .hlist{display:inline;padding-left:1em}img{max-width:100%}td{padding:0 .5em}.admonition{padding:.1em 1em;margin:1em 0}.admonition-title{font-weight:bold}.admonition.note,.admonition.info,.admonition.important{background:#aef}.admonition.todo,.admonition.versionadded,.admonition.tip,.admonition.hint{background:#dfd}.admonition.warning,.admonition.versionchanged,.admonition.deprecated{background:#fd4}.admonition.error,.admonition.danger,.admonition.caution{background:lightpink}</style>
<style media="screen and (min-width: 700px)">@media screen and (min-width:700px){#sidebar{width:30%;height:100vh;overflow:auto;position:sticky;top:0}#content{width:70%;max-width:100ch;padding:3em 4em;border-left:1px solid #ddd}pre code{font-size:1em}.name{font-size:1em}main{display:flex;flex-direction:row-reverse;justify-content:flex-end}.toc ul ul,#index ul ul{padding-left:1em}.toc > ul > li{margin-top:.5em}}</style>
<style media="print">@media print{#sidebar h1{page-break-before:always}.source{display:none}}@media print{*{background:transparent !important;color:#000 !important;box-shadow:none !important;text-shadow:none !important}a[href]:after{content:" (" attr(href) ")";font-size:90%}a[href][title]:after{content:none}abbr[title]:after{content:" (" attr(title) ")"}.ir a:after,a[href^="javascript:"]:after,a[href^="#"]:after{content:""}pre,blockquote{border:1px solid #999;page-break-inside:avoid}thead{display:table-header-group}tr,img{page-break-inside:avoid}img{max-width:100% !important}@page{margin:0.5cm}p,h2,h3{orphans:3;widows:3}h1,h2,h3,h4,h5,h6{page-break-after:avoid}}</style>
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js" integrity="sha512-D9gUyxqja7hBtkWpPWGt9wfbfaMGVt9gnyCvYa+jojwwPHLCzUm5i8rpk7vD7wNee9bA35eYIjobYPaQuKS1MQ==" crossorigin></script>
<script>window.addEventListener('DOMContentLoaded', () => {
hljs.configure({languages: ['bash', 'css', 'diff', 'graphql', 'ini', 'javascript', 'json', 'plaintext', 'python', 'python-repl', 'rust', 'shell', 'sql', 'typescript', 'xml', 'yaml']});
hljs.highlightAll();
/* Collapse source docstrings */
setTimeout(() => {
[...document.querySelectorAll('.hljs.language-python > .hljs-string')]
.filter(el => el.innerHTML.length > 200 && ['"""', "'''"].includes(el.innerHTML.substring(0, 3)))
.forEach(el => {
let d = document.createElement('details');
d.classList.add('hljs-string');
d.innerHTML = '<summary>"""</summary>' + el.innerHTML.substring(3);
el.replaceWith(d);
});
}, 100);
})</script>
</head>
<body>
<main>
<article id="content">
<header>
<h1 class="title">Module <code>piecad.projectbox</code></h1>
</header>
<section id="section-intro">
<p>THIS FEATURE IS SOMEWHAT EXPERIMENTAL, THE API SUBJECT TO CHANGE.</p>
<p>A class for quickly constructing a project box.</p>
<p>Call <code>finish</code> to retrieve the Obj3d of the final box.</p>
<p>See <code>examples</code> to see how to use ProjectBox (`pbox_*).</p>
<p>The general idea is that ProjectBox creates routines that let you position components
in 2D (x, y) on the left, right, front, back, top, bottom of a ProjectBox.
Generally 2D design is easier than 3D.</p>
<p>Components are shapes or holes.
Holes names end in "_hole" or "holes".
When a ProjectBox is finished, all shapes are unioned with the box and
all holes are differenced from the box.</p>
<p>By convention component origins (0, 0) are either centered, or bottom left.
It is a good idea to show the ORIGIN in the components documentation.</p>
</section>
<section>
</section>
<section>
</section>
<section>
</section>
<section>
<h2 class="section-title" id="header-classes">Classes</h2>
<dl>
<dt id="piecad.projectbox.ProjectBox"><code class="flex name class">
<span>class <span class="ident">ProjectBox</span></span>
<span>(</span><span>size: list[float, float, float], wall: float = 2.0, segments: int = -1)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">class ProjectBox:
    &#34;&#34;&#34;
    Quickly create a project box.
    &#34;&#34;&#34;
    def __init__(self,
        size: list[float, float, float],
        wall: float = 2.0,
        segments: int = -1,
    ):
        &#34;&#34;&#34;
        Make a project box with the x (width), y (depth), and z (height) values given in size.

        The dimensions are for the INSIDE of the box.

        The INSIDE of the box will be placed at `(0, 0, 0)`.

        The `wall` parameter specifies the thickness of the major walls of the box.

        For `segments` see the documentation of [`set_default_segments`](index.html#piecad.set_default_segments).

        &lt;iframe width=&#34;100%&#34; height=&#34;380&#34; src=&#34;/examples/projectbox.html&#34;&gt;&lt;/iframe&gt;
        &#34;&#34;&#34;
        if segments == -1:
            segments = config[&#34;DefaultSegments&#34;]
        _chkGE(&#34;segments&#34;, segments, 3)
        _chkV3(&#34;size&#34;, size)
        _chkGE(&#34;wall&#34;, wall, 2.0)

        tiny = 0.5
        iota = 0.1
        self._segments = segments
        self._size = size
        self.w, self.d, self.h = self._size
        self.h = self.h+wall
        self.wall = wall

        def mkwall(dims, ty=None):
            max_sh = self.h - wall
            screw_h = 22 if max_sh &gt;= 22 else max_sh
            screw_top_r = 3.0+iota
            screw_d = 3.0
            screw_r = (screw_d+2*tiny)/2 # 3mm screw hole
            nut_r = 3.0
            nut_h = 2.4*1.2
            rd = (screw_top_r+4*wall)+tiny
            rr = rd/2.0
            off = 4*wall+tiny
            self.corner_offset = 3*rr

            def post(rot):
                post_l = 2*rr
                post_w = 3*wall+tiny
                return difference(
                    union(
                        cylinder(radius=rr, height=self.h),
                        cube([post_l, post_w, self.h]).translate([0, -rr, 0]),
                        cube([post_w, post_l, self.h]).translate([-rr, 0, 0]),
                    ),
                    cylinder(radius=screw_r, height=screw_h).translate([0, 0, self.h-screw_h]),
                    cylinder(radius=rr+4, height=nut_h).piecut(300, 150).translate([0, 0, self.h-nut_h-wall]),
                    cylinder(radius=nut_r, height=nut_h, segments=6).translate([0, 0, self.h-nut_h-wall]),
                ).translate([rr, rr, 0]).rotate([0, 0, rot])

            if ty == &#39;t&#39; or ty == &#39;m&#39;:
                w = dims[0]+2*off
                d = dims[1]+2*off
                h = dims[2]
                o = rounded_rectangle([w, d], rr, segments).extrude(h)
                if ty == &#39;t&#39;:
                    o = union(o,
                       post(0),
                       post(270).translate([0, d, 0]),
                       post(180).translate([w, d, 0]),
                       post(90).translate([w, 0, 0]),
                    )
                    o = difference(
                        o,
                        cube([w-4*rr, wall+tiny, self.h]).translate([2.0*rr,wall,wall]),
                        cube([w-4*rr, wall+tiny, self.h]).translate([2.0*rr,d-2*wall,wall]),
                        cube([wall+tiny, d-4*rr, self.h]).translate([wall, 2.0*rr, wall]),
                        cube([wall+tiny, d-4*rr, self.h]).translate([w-2*wall,2.0*rr,wall]),
                    )
                else:
                    def tbh():
                        chamfer_h = sin(45)*screw_top_r
                        h_chamfered = screw_h if chamfer_h&gt;screw_h else chamfer_h
                        h_remaining = 0 if chamfer_h&gt;screw_h else screw_h-chamfer_h
                        o = union(
                            cylinder(height=0.5, radius=screw_top_r),
                            cone(height=h_chamfered, radius_low=screw_top_r, radius_high=screw_r).translate((0, 0, 0.5)),
                            cylinder(height=h_remaining, radius=screw_r).translate((0, 0, h_chamfered+1)),
                        )
                        return o

                    o = difference(
                        o,
                        tbh().translate([rr, rr, 0]),
                        tbh().translate([w-rr, rr, 0]),
                        tbh().translate([rr, d-rr, 0]),
                        tbh().translate([w-rr, d-rr, 0]),
                    )
                o = o.translate([-off, -off, -wall])
            else:
                w = dims[0]-2*rr-tiny+wall
                d = dims[1]-wall
                h = dims[2]
                o = cube([w, d, h])
                o = o.translate([(dims[0]-w)/2, 0, -wall])
            return o

        self._l_wall = mkwall([self.d, self.h, self.wall])
        self._l_unions = []
        self._l_differences = []
        self._r_wall = mkwall([self.d, self.h, self.wall])
        self._r_unions = []
        self._r_differences = []
        self._f_wall = mkwall([self.w, self.h, self.wall])
        self._f_unions = []
        self._f_differences = []
        self._k_wall = mkwall([self.w, self.h, self.wall])
        self._k_unions = []
        self._k_differences = []
        self._t_wall = mkwall([self.w, self.d, self.wall], &#39;t&#39;)
        self._t_unions = []
        self._t_differences = []
        self._m_wall = mkwall([self.w, self.d, self.wall], &#39;m&#39;)
        self._m_unions = []
        self._m_differences = []


    def left(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the left side of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._l_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._l_differences.append(hole.translate([x, y, 0]))

    def right(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the right side of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._r_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._r_differences.append(hole.translate([x, y, 0]))

    def front(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the front side of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._f_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._f_differences.append(hole.translate([x, y, 0]))

    def back(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the back side of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._k_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._k_differences.append(hole.translate([x, y, 0]))

    def top(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the top of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._t_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._t_differences.append(hole.translate([x, y, 0]))

    def bottom(self, x, y, shape, hole):
        &#34;&#34;&#34;
        Add a component at `x, y` of the bottom of the box.
        If `shape` or `hole` is not present, use `None`.
        &#34;&#34;&#34;
        if shape != None:
            self._m_unions.append(shape.translate([x, y, 0]))
        if hole != None:
            self._m_differences.append(hole.translate([x, y, 0]))

    def finish(self) -&gt; Obj3d:
        &#34;&#34;&#34;
        The `finish` method returns a six-tuple of the parts of the project box:

        ```
        left, right, front, back, top, bottom = ProjectBox((45, 30, 20)).finish()
        ```

        &#34;&#34;&#34;
        def f(box, differences, unions):
            if len(unions) &gt; 0:
                box = union(box, *unions)
            if len(differences) &gt; 0:
                box = difference(box, *differences)
            return box
        return (
                f(self._l_wall, self._l_differences, self._l_unions),
                f(self._r_wall, self._r_differences, self._r_unions),
                f(self._f_wall, self._f_differences, self._f_unions),
                f(self._k_wall, self._k_differences, self._k_unions),
                f(self._t_wall, self._t_differences, self._t_unions),
                f(self._m_wall, self._m_differences, self._m_unions),
                )</code></pre>
</details>
<div class="desc"><p>Quickly create a project box.</p>
<p>Make a project box with the x (width), y (depth), and z (height) values given in size.</p>
<p>The dimensions are for the INSIDE of the box.</p>
<p>The INSIDE of the box will be placed at <code>(0, 0, 0)</code>.</p>
<p>The <code>wall</code> parameter specifies the thickness of the major walls of the box.</p>
<p>For <code>segments</code> see the documentation of <a href="index.html#piecad.set_default_segments"><code>set_default_segments</code></a>.</p>
<iframe width="100%" height="380" src="/examples/projectbox.html"></iframe></div>
<h3>Methods</h3>
<dl>
<dt id="piecad.projectbox.ProjectBox.back"><code class="name flex">
<span>def <span class="ident">back</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def back(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the back side of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._k_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._k_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the back side of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.bottom"><code class="name flex">
<span>def <span class="ident">bottom</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def bottom(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the bottom of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._m_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._m_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the bottom of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.finish"><code class="name flex">
<span>def <span class="ident">finish</span></span>(<span>self) ‑> <a title="piecad.Obj3d" href="../index.html#piecad.Obj3d">Obj3d</a></span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def finish(self) -&gt; Obj3d:
    &#34;&#34;&#34;
    The `finish` method returns a six-tuple of the parts of the project box:

    ```
    left, right, front, back, top, bottom = ProjectBox((45, 30, 20)).finish()
    ```

    &#34;&#34;&#34;
    def f(box, differences, unions):
        if len(unions) &gt; 0:
            box = union(box, *unions)
        if len(differences) &gt; 0:
            box = difference(box, *differences)
        return box
    return (
            f(self._l_wall, self._l_differences, self._l_unions),
            f(self._r_wall, self._r_differences, self._r_unions),
            f(self._f_wall, self._f_differences, self._f_unions),
            f(self._k_wall, self._k_differences, self._k_unions),
            f(self._t_wall, self._t_differences, self._t_unions),
            f(self._m_wall, self._m_differences, self._m_unions),
            )</code></pre>
</details>
<div class="desc"><p>The <code>finish</code> method returns a six-tuple of the parts of the project box:</p>
<pre><code>left, right, front, back, top, bottom = ProjectBox((45, 30, 20)).finish()
</code></pre></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.front"><code class="name flex">
<span>def <span class="ident">front</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def front(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the front side of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._f_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._f_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the front side of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.left"><code class="name flex">
<span>def <span class="ident">left</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def left(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the left side of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._l_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._l_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the left side of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.right"><code class="name flex">
<span>def <span class="ident">right</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def right(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the right side of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._r_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._r_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the right side of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
<dt id="piecad.projectbox.ProjectBox.top"><code class="name flex">
<span>def <span class="ident">top</span></span>(<span>self, x, y, shape, hole)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">def top(self, x, y, shape, hole):
    &#34;&#34;&#34;
    Add a component at `x, y` of the top of the box.
    If `shape` or `hole` is not present, use `None`.
    &#34;&#34;&#34;
    if shape != None:
        self._t_unions.append(shape.translate([x, y, 0]))
    if hole != None:
        self._t_differences.append(hole.translate([x, y, 0]))</code></pre>
</details>
<div class="desc"><p>Add a component at <code>x, y</code> of the top of the box.
If <code>shape</code> or <code>hole</code> is not present, use <code>None</code>.</p></div>
</dd>
</dl>
</dd>
<dt id="piecad.projectbox.pbc"><code class="flex name class">
<span>class <span class="ident">pbc</span></span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">class pbc:
    @staticmethod
    def tap_post(h: float, size_d: float, post_wall=2.0, add_taper=False, z_rot=0):
        &#34;&#34;&#34;
        A post suitable for tapping or using a self-taping screw or bolt.
        ORIGIN: centered

        Parameter `h` is the height of the post (without taper).

        Parameter `size_d` is a diameter because that&#39;s how bolts are usually
        specified. For example a M4 bolt has a 4mm diameter.

        Parameter `post_wall`, how thick (beyond the screw) the wall should be.

        If you are mounting your posts horizontally (from the sides of the box),
        set `add_taper` to `True` and a 45 degree taper is added to the bottom
        of the post to aid in 3d printing.

        By default a tap post&#39;s bottom is centered at (0, 0, 0), BUT, if you
        add a taper then the tap post&#39;s top is centered at (0, 0, 0).

        Parameter `z_rot` is if you want to rotate the post (used in some lids).
        &#34;&#34;&#34;
        inner_d = size_d*0.8 #Possibly snug, but with PLA I prefer that
        outer_d = post_wall*2+size_d
        circ = difference(circle(outer_d/2.0), circle(inner_d/2.0))
        if (add_taper):
            tp = circ.extrude(h*2)
            tp = difference(tp,
                cube([outer_d, outer_d, h*3+2], center=True).rotate([45, 0, z_rot]).translate([0,0,h]))
            return tp.translate([0, 0, -h*2]) 
        else:
            return circ.extrude(h)

    @staticmethod
    def horizontal_slot_hole(w, h, wall=2):
        &#34;&#34;&#34;
        Creates a hole that is a rounded_rectangle.
        Useful for things like a USB connector.

        ORIGIN: centered
        &#34;&#34;&#34;
        slot = rounded_rectangle((w, h), h/2.0).extrude(wall)
        slot = slot.translate([0, 0, -wall]).center([True, True, False])
        return slot

    @staticmethod
    def tapered_bolt_hole(height, size_d):
        &#34;&#34;&#34;
        Creates a hole for a tapered bolt (the top of the head will be flush).

        ORIGIN: centered
        &#34;&#34;&#34;
        bolt_top_r = size_d
        r = size_d/2.0
        chamfer_h = sin(45)*bolt_top_r
        h_chamfered = height if chamfer_h&gt;height else chamfer_h
        h_remaining = 0 if chamfer_h&gt;height else height-chamfer_h
        o = union(
            cylinder(height=1, radius=bolt_top_r),
            cone(height=h_chamfered, radius_low=bolt_top_r, radius_high=r).translate((0, 0, 1)),
            cylinder(height=h_remaining, radius=r*0.80).translate((0, 0, h_chamfered+1)),
        ).rotate((180, 0, 0))
        return o

    @staticmethod
    def hole(r, wall=2):
        &#34;&#34;&#34;
        Creates a negative shape to create a hole.
        (Used in difference, or the &#34;hole&#34; attribute in ProjectBox methods.)

        ORIGIN: centered
        &#34;&#34;&#34;
        return circle(r).extrude(wall).rotate((180, 0, 0))


    @staticmethod
    def wire_tie_loop():
        &#34;&#34;&#34;
        A &#34;horseshoe&#34; sized to pass a wire tie through.
        Useful for holding project boards in place with no screws.

        ORIGIN: centered
        &#34;&#34;&#34;
        tiny = 0.01
        return difference(
            cube([2, 7, 6], center=True),
            cube([2+2*tiny, 3, 2], center=True),
        ).translate([1,3.5,3])

    @staticmethod
    def circular_speaker_grid_holes(radius, wall=2, hole_w=2):
        &#34;&#34;&#34;
        The `radius` is the radius of the speaker grill.
        Also useful for air holes.

        Parameter `wall` specifies the width of the grid holes.
        Parameter `hole_w` specifies the width of the grid holes.

        Works best if speaker `radius` is evenly divisible by `hole_w`.

        ORIGIN: centered
        &#34;&#34;&#34;
        tiny = 0.01
        l = []
        y = -(radius - hole_w)
        while y &lt;= radius - hole_w:
            l.append(
                cube([radius * 2, hole_w, wall + 2 * tiny], center=True).translate([0, y, 0])
            )
            y += 2 * hole_w
        return intersect(
            union(*l), cylinder(radius=radius, height=wall + 2 * tiny, center=True)
        ).translate([0, 0, -(wall / 2) - tiny])</code></pre>
</details>
<div class="desc"></div>
<h3>Static methods</h3>
<dl>
<dt id="piecad.projectbox.pbc.circular_speaker_grid_holes"><code class="name flex">
<span>def <span class="ident">circular_speaker_grid_holes</span></span>(<span>radius, wall=2, hole_w=2)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def circular_speaker_grid_holes(radius, wall=2, hole_w=2):
    &#34;&#34;&#34;
    The `radius` is the radius of the speaker grill.
    Also useful for air holes.

    Parameter `wall` specifies the width of the grid holes.
    Parameter `hole_w` specifies the width of the grid holes.

    Works best if speaker `radius` is evenly divisible by `hole_w`.

    ORIGIN: centered
    &#34;&#34;&#34;
    tiny = 0.01
    l = []
    y = -(radius - hole_w)
    while y &lt;= radius - hole_w:
        l.append(
            cube([radius * 2, hole_w, wall + 2 * tiny], center=True).translate([0, y, 0])
        )
        y += 2 * hole_w
    return intersect(
        union(*l), cylinder(radius=radius, height=wall + 2 * tiny, center=True)
    ).translate([0, 0, -(wall / 2) - tiny])</code></pre>
</details>
<div class="desc"><p>The <code>radius</code> is the radius of the speaker grill.
Also useful for air holes.</p>
<p>Parameter <code>wall</code> specifies the width of the grid holes.
Parameter <code>hole_w</code> specifies the width of the grid holes.</p>
<p>Works best if speaker <code>radius</code> is evenly divisible by <code>hole_w</code>.</p>
<p>ORIGIN: centered</p></div>
</dd>
<dt id="piecad.projectbox.pbc.hole"><code class="name flex">
<span>def <span class="ident">hole</span></span>(<span>r, wall=2)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def hole(r, wall=2):
    &#34;&#34;&#34;
    Creates a negative shape to create a hole.
    (Used in difference, or the &#34;hole&#34; attribute in ProjectBox methods.)

    ORIGIN: centered
    &#34;&#34;&#34;
    return circle(r).extrude(wall).rotate((180, 0, 0))</code></pre>
</details>
<div class="desc"><p>Creates a negative shape to create a hole.
(Used in difference, or the "hole" attribute in ProjectBox methods.)</p>
<p>ORIGIN: centered</p></div>
</dd>
<dt id="piecad.projectbox.pbc.horizontal_slot_hole"><code class="name flex">
<span>def <span class="ident">horizontal_slot_hole</span></span>(<span>w, h, wall=2)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def horizontal_slot_hole(w, h, wall=2):
    &#34;&#34;&#34;
    Creates a hole that is a rounded_rectangle.
    Useful for things like a USB connector.

    ORIGIN: centered
    &#34;&#34;&#34;
    slot = rounded_rectangle((w, h), h/2.0).extrude(wall)
    slot = slot.translate([0, 0, -wall]).center([True, True, False])
    return slot</code></pre>
</details>
<div class="desc"><p>Creates a hole that is a rounded_rectangle.
Useful for things like a USB connector.</p>
<p>ORIGIN: centered</p></div>
</dd>
<dt id="piecad.projectbox.pbc.tap_post"><code class="name flex">
<span>def <span class="ident">tap_post</span></span>(<span>h: float, size_d: float, post_wall=2.0, add_taper=False, z_rot=0)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def tap_post(h: float, size_d: float, post_wall=2.0, add_taper=False, z_rot=0):
    &#34;&#34;&#34;
    A post suitable for tapping or using a self-taping screw or bolt.
    ORIGIN: centered

    Parameter `h` is the height of the post (without taper).

    Parameter `size_d` is a diameter because that&#39;s how bolts are usually
    specified. For example a M4 bolt has a 4mm diameter.

    Parameter `post_wall`, how thick (beyond the screw) the wall should be.

    If you are mounting your posts horizontally (from the sides of the box),
    set `add_taper` to `True` and a 45 degree taper is added to the bottom
    of the post to aid in 3d printing.

    By default a tap post&#39;s bottom is centered at (0, 0, 0), BUT, if you
    add a taper then the tap post&#39;s top is centered at (0, 0, 0).

    Parameter `z_rot` is if you want to rotate the post (used in some lids).
    &#34;&#34;&#34;
    inner_d = size_d*0.8 #Possibly snug, but with PLA I prefer that
    outer_d = post_wall*2+size_d
    circ = difference(circle(outer_d/2.0), circle(inner_d/2.0))
    if (add_taper):
        tp = circ.extrude(h*2)
        tp = difference(tp,
            cube([outer_d, outer_d, h*3+2], center=True).rotate([45, 0, z_rot]).translate([0,0,h]))
        return tp.translate([0, 0, -h*2]) 
    else:
        return circ.extrude(h)</code></pre>
</details>
<div class="desc"><p>A post suitable for tapping or using a self-taping screw or bolt.
ORIGIN: centered</p>
<p>Parameter <code>h</code> is the height of the post (without taper).</p>
<p>Parameter <code>size_d</code> is a diameter because that's how bolts are usually
specified. For example a M4 bolt has a 4mm diameter.</p>
<p>Parameter <code>post_wall</code>, how thick (beyond the screw) the wall should be.</p>
<p>If you are mounting your posts horizontally (from the sides of the box),
set <code>add_taper</code> to <code>True</code> and a 45 degree taper is added to the bottom
of the post to aid in 3d printing.</p>
<p>By default a tap post's bottom is centered at (0, 0, 0), BUT, if you
add a taper then the tap post's top is centered at (0, 0, 0).</p>
<p>Parameter <code>z_rot</code> is if you want to rotate the post (used in some lids).</p></div>
</dd>
<dt id="piecad.projectbox.pbc.tapered_bolt_hole"><code class="name flex">
<span>def <span class="ident">tapered_bolt_hole</span></span>(<span>height, size_d)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def tapered_bolt_hole(height, size_d):
    &#34;&#34;&#34;
    Creates a hole for a tapered bolt (the top of the head will be flush).

    ORIGIN: centered
    &#34;&#34;&#34;
    bolt_top_r = size_d
    r = size_d/2.0
    chamfer_h = sin(45)*bolt_top_r
    h_chamfered = height if chamfer_h&gt;height else chamfer_h
    h_remaining = 0 if chamfer_h&gt;height else height-chamfer_h
    o = union(
        cylinder(height=1, radius=bolt_top_r),
        cone(height=h_chamfered, radius_low=bolt_top_r, radius_high=r).translate((0, 0, 1)),
        cylinder(height=h_remaining, radius=r*0.80).translate((0, 0, h_chamfered+1)),
    ).rotate((180, 0, 0))
    return o</code></pre>
</details>
<div class="desc"><p>Creates a hole for a tapered bolt (the top of the head will be flush).</p>
<p>ORIGIN: centered</p></div>
</dd>
<dt id="piecad.projectbox.pbc.wire_tie_loop"><code class="name flex">
<span>def <span class="ident">wire_tie_loop</span></span>(<span>)</span>
</code></dt>
<dd>
<details class="source">
<summary>
<span>Expand source code</span>
</summary>
<pre><code class="python">@staticmethod
def wire_tie_loop():
    &#34;&#34;&#34;
    A &#34;horseshoe&#34; sized to pass a wire tie through.
    Useful for holding project boards in place with no screws.

    ORIGIN: centered
    &#34;&#34;&#34;
    tiny = 0.01
    return difference(
        cube([2, 7, 6], center=True),
        cube([2+2*tiny, 3, 2], center=True),
    ).translate([1,3.5,3])</code></pre>
</details>
<div class="desc"><p>A "horseshoe" sized to pass a wire tie through.
Useful for holding project boards in place with no screws.</p>
<p>ORIGIN: centered</p></div>
</dd>
</dl>
</dd>
</dl>
</section>
</article>
<nav id="sidebar">
<div class="toc">
<ul></ul>
</div>
<ul id="index">
<li><h3>Super-module</h3>
<ul>
<li><code><a title="piecad" href="../index.html">piecad</a></code></li>
</ul>
</li>
<li><h3><a href="#header-classes">Classes</a></h3>
<ul>
<li>
<h4><code><a title="piecad.projectbox.ProjectBox" href="#piecad.projectbox.ProjectBox">ProjectBox</a></code></h4>
<ul class="two-column">
<li><code><a title="piecad.projectbox.ProjectBox.back" href="#piecad.projectbox.ProjectBox.back">back</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.bottom" href="#piecad.projectbox.ProjectBox.bottom">bottom</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.finish" href="#piecad.projectbox.ProjectBox.finish">finish</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.front" href="#piecad.projectbox.ProjectBox.front">front</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.left" href="#piecad.projectbox.ProjectBox.left">left</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.right" href="#piecad.projectbox.ProjectBox.right">right</a></code></li>
<li><code><a title="piecad.projectbox.ProjectBox.top" href="#piecad.projectbox.ProjectBox.top">top</a></code></li>
</ul>
</li>
<li>
<h4><code><a title="piecad.projectbox.pbc" href="#piecad.projectbox.pbc">pbc</a></code></h4>
<ul class="">
<li><code><a title="piecad.projectbox.pbc.circular_speaker_grid_holes" href="#piecad.projectbox.pbc.circular_speaker_grid_holes">circular_speaker_grid_holes</a></code></li>
<li><code><a title="piecad.projectbox.pbc.hole" href="#piecad.projectbox.pbc.hole">hole</a></code></li>
<li><code><a title="piecad.projectbox.pbc.horizontal_slot_hole" href="#piecad.projectbox.pbc.horizontal_slot_hole">horizontal_slot_hole</a></code></li>
<li><code><a title="piecad.projectbox.pbc.tap_post" href="#piecad.projectbox.pbc.tap_post">tap_post</a></code></li>
<li><code><a title="piecad.projectbox.pbc.tapered_bolt_hole" href="#piecad.projectbox.pbc.tapered_bolt_hole">tapered_bolt_hole</a></code></li>
<li><code><a title="piecad.projectbox.pbc.wire_tie_loop" href="#piecad.projectbox.pbc.wire_tie_loop">wire_tie_loop</a></code></li>
</ul>
</li>
</ul>
</li>
</ul>
</nav>
</main>
<footer id="footer">
<p>Generated by <a href="https://pdoc3.github.io/pdoc" title="pdoc: Python API documentation generator"><cite>pdoc</cite> 0.11.6</a>.</p>
</footer>
</body>
</html>
