# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/moveit_msgs/srv/load_map.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9make87_messages_ros2/jazzy/moveit_msgs/srv/load_map.proto\x12*make87_messages_ros2.jazzy.moveit_msgs.srv\"\"\n\x0eLoadMapRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\"\n\x0fLoadMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.moveit_msgs.srv.load_map_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOADMAPREQUEST']._serialized_start=105
  _globals['_LOADMAPREQUEST']._serialized_end=139
  _globals['_LOADMAPRESPONSE']._serialized_start=141
  _globals['_LOADMAPRESPONSE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
