(define (domain dungeon)
        (:requirements :equality :typing :negative-preconditions :disjunctive-preconditions)
        (:types locationed room - object person switch - locationed)
        (:predicates (connected ?a ?b - room ?s - switch)
                     (at ?l - locationed ?r - room)
                     (on ?s - switch))
        (:action move
        :parameters (?p - person ?from ?to - room ?s - switch)
        :precondition (and (at ?p ?from)
                           (not (= ?from ?to))
                           (or (connected ?from ?to ?s)
                               (connected ?to ?from ?s))
                           (on ?s))
        :effect (and (at ?p ?to)
                     (not (at ?p ?from))))
        (:action turn-on
        :parameters (?p - person ?s - switch ?r - room)
        :precondition (and (at ?p ?r)
                           (at ?s ?r)
                           (not (on ?s)))
        :effect (on ?s)))