# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/rosbag2_interfaces/srv/pause.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?make87_messages_ros2/rolling/rosbag2_interfaces/srv/pause.proto\x12\x33make87_messages_ros2.rolling.rosbag2_interfaces.srv\"\x0e\n\x0cPauseRequest\"\x0f\n\rPauseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.rosbag2_interfaces.srv.pause_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PAUSEREQUEST']._serialized_start=120
  _globals['_PAUSEREQUEST']._serialized_end=134
  _globals['_PAUSERESPONSE']._serialized_start=136
  _globals['_PAUSERESPONSE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
