# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/humble/ds_dbw_msgs/msg/throttle_info.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/humble/ds_dbw_msgs/msg/throttle_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.ds_dbw_msgs.msg import drive_mode_pb2 as make87__messages__ros2_dot_humble_dot_ds__dbw__msgs_dot_msg_dot_drive__mode__pb2
from make87_messages_ros2.humble.ds_dbw_msgs.msg import gear_num_pb2 as make87__messages__ros2_dot_humble_dot_ds__dbw__msgs_dot_msg_dot_gear__num__pb2
from make87_messages_ros2.humble.ds_dbw_msgs.msg import one_pedal_pb2 as make87__messages__ros2_dot_humble_dot_ds__dbw__msgs_dot_msg_dot_one__pedal__pb2
from make87_messages_ros2.humble.ds_dbw_msgs.msg import quality_pb2 as make87__messages__ros2_dot_humble_dot_ds__dbw__msgs_dot_msg_dot_quality__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?make87_messages_ros2/humble/ds_dbw_msgs/msg/throttle_info.proto\x12+make87_messages_ros2.humble.ds_dbw_msgs.msg\x1a!make87_messages/core/header.proto\x1a<make87_messages_ros2/humble/ds_dbw_msgs/msg/drive_mode.proto\x1a:make87_messages_ros2/humble/ds_dbw_msgs/msg/gear_num.proto\x1a;make87_messages_ros2/humble/ds_dbw_msgs/msg/one_pedal.proto\x1a\x39make87_messages_ros2/humble/ds_dbw_msgs/msg/quality.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\xdb\x03\n\x0cThrottleInfo\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12\x16\n\x0e\x61\x63\x63\x65l_pedal_pc\x18\x03 \x01(\x02\x12L\n\x0e\x61\x63\x63\x65l_pedal_qf\x18\x04 \x01(\x0b\x32\x34.make87_messages_ros2.humble.ds_dbw_msgs.msg.Quality\x12H\n\tone_pedal\x18\x05 \x01(\x0b\x32\x35.make87_messages_ros2.humble.ds_dbw_msgs.msg.OnePedal\x12\x12\n\nengine_rpm\x18\x06 \x01(\x02\x12J\n\ndrive_mode\x18\x07 \x01(\x0b\x32\x36.make87_messages_ros2.humble.ds_dbw_msgs.msg.DriveMode\x12\x46\n\x08gear_num\x18\x08 \x01(\x0b\x32\x34.make87_messages_ros2.humble.ds_dbw_msgs.msg.GearNumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.ds_dbw_msgs.msg.throttle_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THROTTLEINFO']._serialized_start=445
  _globals['_THROTTLEINFO']._serialized_end=920
# @@protoc_insertion_point(module_scope)
