# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/cartographer_ros_msgs/srv/write_state.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/cartographer_ros_msgs/srv/write_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.cartographer_ros_msgs.msg import status_response_pb2 as make87__messages__ros2_dot_jazzy_dot_cartographer__ros__msgs_dot_msg_dot_status__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/jazzy/cartographer_ros_msgs/srv/write_state.proto\x12\x34make87_messages_ros2.jazzy.cartographer_ros_msgs.srv\x1aJmake87_messages_ros2/jazzy/cartographer_ros_msgs/msg/status_response.proto\"I\n\x11WriteStateRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\"\n\x1ainclude_unfinished_submaps\x18\x02 \x01(\x08\"j\n\x12WriteStateResponse\x12T\n\x06status\x18\x01 \x01(\x0b\x32\x44.make87_messages_ros2.jazzy.cartographer_ros_msgs.msg.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.cartographer_ros_msgs.srv.write_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITESTATEREQUEST']._serialized_start=204
  _globals['_WRITESTATEREQUEST']._serialized_end=277
  _globals['_WRITESTATERESPONSE']._serialized_start=279
  _globals['_WRITESTATERESPONSE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
