"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "apideck-accounting-unify"
__version__: str = "0.16.2"
__openapi_doc_version__: str = "10.17.2"
__gen_version__: str = "2.623.4"
__user_agent__: str = (
    "speakeasy-sdk/python 0.16.2 2.623.4 10.17.2 apideck-accounting-unify"
)

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
