# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/autoware_planning_msgs/msg/path_point.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.geometry_msgs.msg import pose_pb2 as make87__messages__ros2_dot_jazzy_dot_geometry__msgs_dot_msg_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/jazzy/autoware_planning_msgs/msg/path_point.proto\x12\x35make87_messages_ros2.jazzy.autoware_planning_msgs.msg\x1a\x37make87_messages_ros2/jazzy/geometry_msgs/msg/pose.proto\"\xba\x01\n\tPathPoint\x12@\n\x04pose\x18\x01 \x01(\x0b\x32\x32.make87_messages_ros2.jazzy.geometry_msgs.msg.Pose\x12!\n\x19longitudinal_velocity_mps\x18\x02 \x01(\x02\x12\x1c\n\x14lateral_velocity_mps\x18\x03 \x01(\x02\x12\x18\n\x10heading_rate_rps\x18\x04 \x01(\x02\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.autoware_planning_msgs.msg.path_point_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATHPOINT']._serialized_start=187
  _globals['_PATHPOINT']._serialized_end=373
# @@protoc_insertion_point(module_scope)
