# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/humble/mobileye_560_660_msgs/msg/aftermarket_lane.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/humble/mobileye_560_660_msgs/msg/aftermarket_lane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLmake87_messages_ros2/humble/mobileye_560_660_msgs/msg/aftermarket_lane.proto\x12\x35make87_messages_ros2.humble.mobileye_560_660_msgs.msg\x1a!make87_messages/core/header.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\xec\x02\n\x0f\x41\x66termarketLane\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12\x1c\n\x14lane_confidence_left\x18\x03 \x01(\r\x12\x1a\n\x12ldw_available_left\x18\x04 \x01(\x08\x12\x16\n\x0elane_type_left\x18\x05 \x01(\r\x12\x1d\n\x15\x64istance_to_left_lane\x18\x06 \x01(\x02\x12\x1d\n\x15lane_confidence_right\x18\x07 \x01(\r\x12\x1b\n\x13ldw_available_right\x18\x08 \x01(\x08\x12\x17\n\x0flane_type_right\x18\t \x01(\r\x12\x1e\n\x16\x64istance_to_right_lane\x18\n \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.mobileye_560_660_msgs.msg.aftermarket_lane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AFTERMARKETLANE']._serialized_start=226
  _globals['_AFTERMARKETLANE']._serialized_end=590
# @@protoc_insertion_point(module_scope)
