# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _RTKPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkPhaseGatingImageFilterPython
else:
    import _rtkPhaseGatingImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.itkPointPython
import itk.itkFixedArrayPython
import itk.itkVectorPython
import itk.vnl_vector_refPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.rtkSubSelectImageFilterPython
import itk.itkImageToImageFilterAPython
import itk.itkImageSourcePython
import itk.itkVectorImagePython
import itk.itkImagePython
import itk.itkRGBPixelPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkRGBAPixelPython
import itk.itkIndexPython
import itk.itkImageRegionPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVariableLengthVectorPython
import itk.itkPhasedArray3DSpecialCoordinatesImagePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython
import itk.rtkThreeDCircularProjectionGeometryPython
import itk.rtkProjectionGeometryPython
import itk.itkImageRTKPython
import itk.itkImageBaseRTKPython
import itk.itkImageRegionRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.itkPointRTKPython

def rtkPhaseGatingImageFilterID3_New():
    return rtkPhaseGatingImageFilterID3.New()

class rtkPhaseGatingImageFilterID3(itk.rtkSubSelectImageFilterPython.rtkSubSelectImageFilterID3):
    r"""Proxy of C++ rtkPhaseGatingImageFilterID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> rtkPhaseGatingImageFilterID3_Pointer"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> rtkPhaseGatingImageFilterID3_Pointer"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_Clone(self)

    def SetPhasesFileName(self, _arg):
        r"""
        SetPhasesFileName(self, _arg)

        Parameters
        ----------
        _arg: std::string

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_SetPhasesFileName(self, _arg)

    def GetPhasesFileName(self):
        r"""GetPhasesFileName(self) -> std::string"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetPhasesFileName(self)

    def SetGatingWindowWidth(self, _arg):
        r"""
        SetGatingWindowWidth(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_SetGatingWindowWidth(self, _arg)

    def GetGatingWindowWidth(self):
        r"""GetGatingWindowWidth(self) -> float"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetGatingWindowWidth(self)

    def SetGatingWindowCenter(self, _arg):
        r"""
        SetGatingWindowCenter(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_SetGatingWindowCenter(self, _arg)

    def GetGatingWindowCenter(self):
        r"""GetGatingWindowCenter(self) -> float"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetGatingWindowCenter(self)

    def SetGatingWindowShape(self, _arg):
        r"""
        SetGatingWindowShape(self, _arg)

        Parameters
        ----------
        _arg: int

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_SetGatingWindowShape(self, _arg)

    def GetGatingWindowShape(self):
        r"""GetGatingWindowShape(self) -> int"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetGatingWindowShape(self)

    def GetGatingWeights(self):
        r"""GetGatingWeights(self) -> vectorF"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetGatingWeights(self)

    def GetGatingWeightsOnSelectedProjections(self):
        r"""GetGatingWeightsOnSelectedProjections(self) -> vectorF"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_GetGatingWeightsOnSelectedProjections(self)
    __swig_destroy__ = _rtkPhaseGatingImageFilterPython.delete_rtkPhaseGatingImageFilterID3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> rtkPhaseGatingImageFilterID3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_cast(obj)

    def New(*args, **kargs):
        """New() -> rtkPhaseGatingImageFilterID3

        Create a new object of the class rtkPhaseGatingImageFilterID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkPhaseGatingImageFilterID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkPhaseGatingImageFilterID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkPhaseGatingImageFilterID3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkPhaseGatingImageFilterID3 in _rtkPhaseGatingImageFilterPython:
_rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterID3_swigregister(rtkPhaseGatingImageFilterID3)

def rtkPhaseGatingImageFilterIF3_New():
    return rtkPhaseGatingImageFilterIF3.New()

class rtkPhaseGatingImageFilterIF3(itk.rtkSubSelectImageFilterPython.rtkSubSelectImageFilterIF3):
    r"""Proxy of C++ rtkPhaseGatingImageFilterIF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> rtkPhaseGatingImageFilterIF3_Pointer"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3___New_orig__()

    def Clone(self):
        r"""Clone(self) -> rtkPhaseGatingImageFilterIF3_Pointer"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_Clone(self)

    def SetPhasesFileName(self, _arg):
        r"""
        SetPhasesFileName(self, _arg)

        Parameters
        ----------
        _arg: std::string

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_SetPhasesFileName(self, _arg)

    def GetPhasesFileName(self):
        r"""GetPhasesFileName(self) -> std::string"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetPhasesFileName(self)

    def SetGatingWindowWidth(self, _arg):
        r"""
        SetGatingWindowWidth(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_SetGatingWindowWidth(self, _arg)

    def GetGatingWindowWidth(self):
        r"""GetGatingWindowWidth(self) -> float"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetGatingWindowWidth(self)

    def SetGatingWindowCenter(self, _arg):
        r"""
        SetGatingWindowCenter(self, _arg)

        Parameters
        ----------
        _arg: float

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_SetGatingWindowCenter(self, _arg)

    def GetGatingWindowCenter(self):
        r"""GetGatingWindowCenter(self) -> float"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetGatingWindowCenter(self)

    def SetGatingWindowShape(self, _arg):
        r"""
        SetGatingWindowShape(self, _arg)

        Parameters
        ----------
        _arg: int

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_SetGatingWindowShape(self, _arg)

    def GetGatingWindowShape(self):
        r"""GetGatingWindowShape(self) -> int"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetGatingWindowShape(self)

    def GetGatingWeights(self):
        r"""GetGatingWeights(self) -> vectorF"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetGatingWeights(self)

    def GetGatingWeightsOnSelectedProjections(self):
        r"""GetGatingWeightsOnSelectedProjections(self) -> vectorF"""
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_GetGatingWeightsOnSelectedProjections(self)
    __swig_destroy__ = _rtkPhaseGatingImageFilterPython.delete_rtkPhaseGatingImageFilterIF3

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> rtkPhaseGatingImageFilterIF3

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_cast(obj)

    def New(*args, **kargs):
        """New() -> rtkPhaseGatingImageFilterIF3

        Create a new object of the class rtkPhaseGatingImageFilterIF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkPhaseGatingImageFilterIF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkPhaseGatingImageFilterIF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkPhaseGatingImageFilterIF3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkPhaseGatingImageFilterIF3 in _rtkPhaseGatingImageFilterPython:
_rtkPhaseGatingImageFilterPython.rtkPhaseGatingImageFilterIF3_swigregister(rtkPhaseGatingImageFilterIF3)

from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def phase_gating_image_filter(*args: itkt.ImageLike,  phases_file_name: str=..., gating_window_width: float=..., gating_window_center: float=..., gating_window_shape: int=..., input_projection_stack: itkt.Image=..., input_geometry=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for PhaseGatingImageFilter"""
    import itk

    kwarg_typehints = { 'phases_file_name':phases_file_name,'gating_window_width':gating_window_width,'gating_window_center':gating_window_center,'gating_window_shape':gating_window_shape,'input_projection_stack':input_projection_stack,'input_geometry':input_geometry }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.PhaseGatingImageFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def phase_gating_image_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.RTK.PhaseGatingImageFilter
    phase_gating_image_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    phase_gating_image_filter.__doc__ = filter_object.__doc__



