# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/geographic_msgs/msg/geographic_map_changes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.geographic_msgs.msg import geographic_map_pb2 as make87__messages__ros2_dot_humble_dot_geographic__msgs_dot_msg_dot_geographic__map__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2
from make87_messages_ros2.humble.unique_identifier_msgs.msg import uuid_pb2 as make87__messages__ros2_dot_humble_dot_unique__identifier__msgs_dot_msg_dot_uuid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLmake87_messages_ros2/humble/geographic_msgs/msg/geographic_map_changes.proto\x12/make87_messages_ros2.humble.geographic_msgs.msg\x1a!make87_messages/core/header.proto\x1a\x44make87_messages_ros2/humble/geographic_msgs/msg/geographic_map.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\x1a\x41make87_messages_ros2/humble/unique_identifier_msgs/msg/uuid.proto\"\xa9\x02\n\x14GeographicMapChanges\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12M\n\x05\x64iffs\x18\x03 \x01(\x0b\x32>.make87_messages_ros2.humble.geographic_msgs.msg.GeographicMap\x12M\n\x07\x64\x65letes\x18\x04 \x03(\x0b\x32<.make87_messages_ros2.humble.unique_identifier_msgs.msg.UUIDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.geographic_msgs.msg.geographic_map_changes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GEOGRAPHICMAPCHANGES']._serialized_start=357
  _globals['_GEOGRAPHICMAPCHANGES']._serialized_end=654
# @@protoc_insertion_point(module_scope)
