# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/ur_dashboard_msgs/srv/get_safety_mode.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/ur_dashboard_msgs/srv/get_safety_mode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.ur_dashboard_msgs.msg import safety_mode_pb2 as make87__messages__ros2_dot_jazzy_dot_ur__dashboard__msgs_dot_msg_dot_safety__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/jazzy/ur_dashboard_msgs/srv/get_safety_mode.proto\x12\x30make87_messages_ros2.jazzy.ur_dashboard_msgs.srv\x1a\x42make87_messages_ros2/jazzy/ur_dashboard_msgs/msg/safety_mode.proto\"\x16\n\x14GetSafetyModeRequest\"\x8b\x01\n\x15GetSafetyModeResponse\x12Q\n\x0bsafety_mode\x18\x01 \x01(\x0b\x32<.make87_messages_ros2.jazzy.ur_dashboard_msgs.msg.SafetyMode\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.ur_dashboard_msgs.srv.get_safety_mode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSAFETYMODEREQUEST']._serialized_start=192
  _globals['_GETSAFETYMODEREQUEST']._serialized_end=214
  _globals['_GETSAFETYMODERESPONSE']._serialized_start=217
  _globals['_GETSAFETYMODERESPONSE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
