def generate_note_id() -> str: ...
def pixels_to_flicks(pixels: float, pixels_per_beat: float, tempo: float) -> float: ...
def pixels_to_seconds(pixels: float, pixels_per_beat: float, tempo: float) -> float: ...
def pixels_to_beats(pixels: float, pixels_per_beat: float) -> float: ...
def pixels_to_ticks(pixels: float, pixels_per_beat: float, ppqn: int = 480) -> int: ...
def pixels_to_samples(pixels: float, pixels_per_beat: float, tempo: float, sample_rate: int = 44100) -> int: ...
def calculate_all_timing_data(pixels: float, pixels_per_beat: float, tempo: float, sample_rate: int = 44100, ppqn: int = 480) -> dict: ...
def create_note_with_timing(note_id: str, start_pixels: float, duration_pixels: float, pitch: int, velocity: int, lyric: str, pixels_per_beat: float = 80, tempo: float = 120, sample_rate: int = 44100, ppqn: int = 480) -> dict: ...
