# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/sbg_driver/msg/sbg_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.sbg_driver.msg import sbg_status_aiding_pb2 as make87__messages__ros2_dot_jazzy_dot_sbg__driver_dot_msg_dot_sbg__status__aiding__pb2
from make87_messages_ros2.jazzy.sbg_driver.msg import sbg_status_com_pb2 as make87__messages__ros2_dot_jazzy_dot_sbg__driver_dot_msg_dot_sbg__status__com__pb2
from make87_messages_ros2.jazzy.sbg_driver.msg import sbg_status_general_pb2 as make87__messages__ros2_dot_jazzy_dot_sbg__driver_dot_msg_dot_sbg__status__general__pb2
from make87_messages_ros2.jazzy.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_jazzy_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:make87_messages_ros2/jazzy/sbg_driver/msg/sbg_status.proto\x12)make87_messages_ros2.jazzy.sbg_driver.msg\x1a\x41make87_messages_ros2/jazzy/sbg_driver/msg/sbg_status_aiding.proto\x1a>make87_messages_ros2/jazzy/sbg_driver/msg/sbg_status_com.proto\x1a\x42make87_messages_ros2/jazzy/sbg_driver/msg/sbg_status_general.proto\x1a\x34make87_messages_ros2/jazzy/std_msgs/msg/header.proto\"\xd5\x02\n\tSbgStatus\x12?\n\x06header\x18\x01 \x01(\x0b\x32/.make87_messages_ros2.jazzy.std_msgs.msg.Header\x12\x12\n\ntime_stamp\x18\x02 \x01(\r\x12S\n\x0estatus_general\x18\x03 \x01(\x0b\x32;.make87_messages_ros2.jazzy.sbg_driver.msg.SbgStatusGeneral\x12K\n\nstatus_com\x18\x04 \x01(\x0b\x32\x37.make87_messages_ros2.jazzy.sbg_driver.msg.SbgStatusCom\x12Q\n\rstatus_aiding\x18\x05 \x01(\x0b\x32:.make87_messages_ros2.jazzy.sbg_driver.msg.SbgStatusAidingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.sbg_driver.msg.sbg_status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SBGSTATUS']._serialized_start=359
  _globals['_SBGSTATUS']._serialized_end=700
# @@protoc_insertion_point(module_scope)
