# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/humble/kartech_linear_actuator_msgs/msg/report_poll_req.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/humble/kartech_linear_actuator_msgs/msg/report_poll_req.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.kartech_linear_actuator_msgs.msg import report_index_pb2 as make87__messages__ros2_dot_humble_dot_kartech__linear__actuator__msgs_dot_msg_dot_report__index__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nRmake87_messages_ros2/humble/kartech_linear_actuator_msgs/msg/report_poll_req.proto\x12<make87_messages_ros2.humble.kartech_linear_actuator_msgs.msg\x1a!make87_messages/core/header.proto\x1aOmake87_messages_ros2/humble/kartech_linear_actuator_msgs/msg/report_index.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\xf8\x01\n\rReportPollReq\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12\x0f\n\x07\x63onfirm\x18\x03 \x01(\x08\x12\x61\n\x0ereport_indices\x18\x04 \x03(\x0b\x32I.make87_messages_ros2.humble.kartech_linear_actuator_msgs.msg.ReportIndexb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.kartech_linear_actuator_msgs.msg.report_poll_req_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTPOLLREQ']._serialized_start=320
  _globals['_REPORTPOLLREQ']._serialized_end=568
# @@protoc_insertion_point(module_scope)
