# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/moveit_msgs/msg/motion_sequence_request.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/moveit_msgs/msg/motion_sequence_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.moveit_msgs.msg import motion_sequence_item_pb2 as make87__messages__ros2_dot_jazzy_dot_moveit__msgs_dot_msg_dot_motion__sequence__item__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHmake87_messages_ros2/jazzy/moveit_msgs/msg/motion_sequence_request.proto\x12*make87_messages_ros2.jazzy.moveit_msgs.msg\x1a\x45make87_messages_ros2/jazzy/moveit_msgs/msg/motion_sequence_item.proto\"f\n\x15MotionSequenceRequest\x12M\n\x05items\x18\x01 \x03(\x0b\x32>.make87_messages_ros2.jazzy.moveit_msgs.msg.MotionSequenceItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.moveit_msgs.msg.motion_sequence_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTIONSEQUENCEREQUEST']._serialized_start=191
  _globals['_MOTIONSEQUENCEREQUEST']._serialized_end=293
# @@protoc_insertion_point(module_scope)
