# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/geometry_msgs/msg/accel_stamped.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.rolling.geometry_msgs.msg import accel_pb2 as make87__messages__ros2_dot_rolling_dot_geometry__msgs_dot_msg_dot_accel__pb2
from make87_messages_ros2.rolling.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_rolling_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBmake87_messages_ros2/rolling/geometry_msgs/msg/accel_stamped.proto\x12.make87_messages_ros2.rolling.geometry_msgs.msg\x1a:make87_messages_ros2/rolling/geometry_msgs/msg/accel.proto\x1a\x36make87_messages_ros2/rolling/std_msgs/msg/header.proto\"\x97\x01\n\x0c\x41\x63\x63\x65lStamped\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.make87_messages_ros2.rolling.std_msgs.msg.Header\x12\x44\n\x05\x61\x63\x63\x65l\x18\x02 \x01(\x0b\x32\x35.make87_messages_ros2.rolling.geometry_msgs.msg.Accelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.geometry_msgs.msg.accel_stamped_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ACCELSTAMPED']._serialized_start=235
  _globals['_ACCELSTAMPED']._serialized_end=386
# @@protoc_insertion_point(module_scope)
