import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_bc31e88fcc(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_e9028667c9():spartaqube_cli.list()
@app.command()
def sparta_aa21a94c63():spartaqube_cli.sparta_aa21a94c63()
@app.command()
def sparta_6f56ae7aa6():print('Hello world!')
if __name__=='__main__':app()