# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/robot_localization/srv/set_pose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.geometry_msgs.msg import pose_with_covariance_stamped_pb2 as make87__messages__ros2_dot_jazzy_dot_geometry__msgs_dot_msg_dot_pose__with__covariance__stamped__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@make87_messages_ros2/jazzy/robot_localization/srv/set_pose.proto\x12\x31make87_messages_ros2.jazzy.robot_localization.srv\x1aOmake87_messages_ros2/jazzy/geometry_msgs/msg/pose_with_covariance_stamped.proto\"g\n\x0eSetPoseRequest\x12U\n\x04pose\x18\x01 \x01(\x0b\x32G.make87_messages_ros2.jazzy.geometry_msgs.msg.PoseWithCovarianceStamped\"\x11\n\x0fSetPoseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.robot_localization.srv.set_pose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SETPOSEREQUEST']._serialized_start=200
  _globals['_SETPOSEREQUEST']._serialized_end=303
  _globals['_SETPOSERESPONSE']._serialized_start=305
  _globals['_SETPOSERESPONSE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
