# Constants for TC-720 OEM
SETPOINT_CMD = "T={value:.2f}\r"
GET_SETPOINT_CMD = "T?\r"
GET_CURRENT_TEMP_CMD = "C?\r"

DEFAULT_BAUDRATE = 9600
DEFAULT_BYTESIZE = 8
DEFAULT_PARITY = 'n'
DEFAULT_STOPBITS = 1
DEFAULT_TIMEOUT = 1.0
