# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _RTKPython



from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython
else:
    import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


if _swig_python_version_info[0:2] >= (3, 3):
    import collections.abc
else:
    import collections

import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_matrixPython
import itk.itkPointPython
import itk.vnl_vector_refPython
import itk.itkFixedArrayPython
import itk.itkVectorPython
import itk.itkCovariantVectorPython
import itk.itkImageRTKPython
import itk.itkIndexPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkImagePython
import itk.itkRGBAPixelPython
import itk.itkRGBPixelPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkImageRegionPython
import itk.itkImageBaseRTKPython
import itk.itkPointRTKPython
import itk.itkImageRegionRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkVectorImageRTKPython
import itk.itkImageToImageFilterAPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkPhasedArray3DSpecialCoordinatesImagePython
import itk.itkImageToImageFilterCommonPython

def rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_New():
    return rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2.New()

class rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterVID3VID3):
    r"""Proxy of C++ rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_Clone(self)

    def SetInputDecomposedProjections(self, DecomposedProjections):
        r"""
        SetInputDecomposedProjections(self, DecomposedProjections)

        Parameters
        ----------
        DecomposedProjections: itkImageBase3 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetInputDecomposedProjections(self, DecomposedProjections)

    def GetInputDecomposedProjections(self):
        r"""GetInputDecomposedProjections(self) -> itkVectorImageD3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetInputDecomposedProjections(self)

    def SetInputMeasuredProjections(self, MeasuredProjections):
        r"""
        SetInputMeasuredProjections(self, MeasuredProjections)

        Parameters
        ----------
        MeasuredProjections: itkImageBase3 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetInputMeasuredProjections(self, MeasuredProjections)

    def GetInputMeasuredProjections(self):
        r"""GetInputMeasuredProjections(self) -> itkVectorImageD3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetInputMeasuredProjections(self)

    def SetDetectorResponse(self, DetectorResponse):
        r"""
        SetDetectorResponse(self, DetectorResponse)

        Parameters
        ----------
        DetectorResponse: itkImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetDetectorResponse(self, DetectorResponse)

    def GetDetectorResponse(self):
        r"""GetDetectorResponse(self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetDetectorResponse(self)

    def SetMaterialAttenuations(self, MaterialAttenuations):
        r"""
        SetMaterialAttenuations(self, MaterialAttenuations)

        Parameters
        ----------
        MaterialAttenuations: itkImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetMaterialAttenuations(self, MaterialAttenuations)

    def GetMaterialAttenuations(self):
        r"""GetMaterialAttenuations(self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetMaterialAttenuations(self)

    def SetInputIncidentSpectrum(self, *args):
        r"""
        SetInputIncidentSpectrum(self, IncidentSpectrum)

        Parameters
        ----------
        IncidentSpectrum: itkImageF3 const *

        SetInputIncidentSpectrum(self, IncidentSpectrum)

        Parameters
        ----------
        IncidentSpectrum: itkVectorImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetInputIncidentSpectrum(self, *args)

    def SetInputSecondIncidentSpectrum(self, *args):
        r"""
        SetInputSecondIncidentSpectrum(self, SecondIncidentSpectrum)

        Parameters
        ----------
        SecondIncidentSpectrum: itkImageF3 const *

        SetInputSecondIncidentSpectrum(self, SecondIncidentSpectrum)

        Parameters
        ----------
        SecondIncidentSpectrum: itkVectorImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetInputSecondIncidentSpectrum(self, *args)

    def GetInputIncidentSpectrum(self):
        r"""GetInputIncidentSpectrum(self) -> itkImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetInputIncidentSpectrum(self)

    def GetInputSecondIncidentSpectrum(self):
        r"""GetInputSecondIncidentSpectrum(self) -> itkImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetInputSecondIncidentSpectrum(self)

    def GetNumberOfIterations(self):
        r"""GetNumberOfIterations(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetNumberOfIterations(self)

    def SetNumberOfIterations(self, _arg):
        r"""
        SetNumberOfIterations(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetNumberOfIterations(self, _arg)

    def SetNumberOfEnergies(self, _arg):
        r"""
        SetNumberOfEnergies(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetNumberOfEnergies(self, _arg)

    def GetNumberOfEnergies(self):
        r"""GetNumberOfEnergies(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetNumberOfEnergies(self)

    def SetNumberOfMaterials(self, _arg):
        r"""
        SetNumberOfMaterials(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetNumberOfMaterials(self, _arg)

    def GetNumberOfMaterials(self):
        r"""GetNumberOfMaterials(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetNumberOfMaterials(self)

    def SetOptimizeWithRestarts(self, _arg):
        r"""
        SetOptimizeWithRestarts(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetOptimizeWithRestarts(self, _arg)

    def GetOptimizeWithRestarts(self):
        r"""GetOptimizeWithRestarts(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetOptimizeWithRestarts(self)

    def SetThresholds(self, _arg):
        r"""
        SetThresholds(self, _arg)

        Parameters
        ----------
        _arg: itkVariableLengthVectorD

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetThresholds(self, _arg)

    def GetThresholds(self):
        r"""GetThresholds(self) -> itkVariableLengthVectorD"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetThresholds(self)

    def SetNumberOfSpectralBins(self, _arg):
        r"""
        SetNumberOfSpectralBins(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetNumberOfSpectralBins(self, _arg)

    def GetNumberOfSpectralBins(self):
        r"""GetNumberOfSpectralBins(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetNumberOfSpectralBins(self)

    def SetOutputInverseCramerRaoLowerBound(self, _arg):
        r"""
        SetOutputInverseCramerRaoLowerBound(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetOutputInverseCramerRaoLowerBound(self, _arg)

    def GetOutputInverseCramerRaoLowerBound(self):
        r"""GetOutputInverseCramerRaoLowerBound(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetOutputInverseCramerRaoLowerBound(self)

    def SetOutputFischerMatrix(self, _arg):
        r"""
        SetOutputFischerMatrix(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetOutputFischerMatrix(self, _arg)

    def GetOutputFischerMatrix(self):
        r"""GetOutputFischerMatrix(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetOutputFischerMatrix(self)

    def SetLogTransformEachBin(self, _arg):
        r"""
        SetLogTransformEachBin(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetLogTransformEachBin(self, _arg)

    def GetLogTransformEachBin(self):
        r"""GetLogTransformEachBin(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetLogTransformEachBin(self)

    def SetGuessInitialization(self, _arg):
        r"""
        SetGuessInitialization(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetGuessInitialization(self, _arg)

    def GetGuessInitialization(self):
        r"""GetGuessInitialization(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetGuessInitialization(self)

    def SetIsSpectralCT(self, _arg):
        r"""
        SetIsSpectralCT(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_SetIsSpectralCT(self, _arg)

    def GetIsSpectralCT(self):
        r"""GetIsSpectralCT(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_GetIsSpectralCT(self)
    __swig_destroy__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.delete_rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_cast(obj)

    def New(*args, **kargs):
        """New() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2

        Create a new object of the class rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2 in _rtkSimplexSpectralProjectionsDecompositionImageFilterPython:
_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2_swigregister(rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3IF3IF2IF2)

def rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_New():
    return rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2.New()

class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterVIF3VIF3):
    r"""Proxy of C++ rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    @staticmethod
    def __New_orig__():
        r"""__New_orig__() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2___New_orig__()

    def Clone(self):
        r"""Clone(self) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_Pointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_Clone(self)

    def SetInputDecomposedProjections(self, DecomposedProjections):
        r"""
        SetInputDecomposedProjections(self, DecomposedProjections)

        Parameters
        ----------
        DecomposedProjections: itkImageBase3 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetInputDecomposedProjections(self, DecomposedProjections)

    def GetInputDecomposedProjections(self):
        r"""GetInputDecomposedProjections(self) -> itkVectorImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetInputDecomposedProjections(self)

    def SetInputMeasuredProjections(self, MeasuredProjections):
        r"""
        SetInputMeasuredProjections(self, MeasuredProjections)

        Parameters
        ----------
        MeasuredProjections: itkImageBase3 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetInputMeasuredProjections(self, MeasuredProjections)

    def GetInputMeasuredProjections(self):
        r"""GetInputMeasuredProjections(self) -> itkVectorImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetInputMeasuredProjections(self)

    def SetDetectorResponse(self, DetectorResponse):
        r"""
        SetDetectorResponse(self, DetectorResponse)

        Parameters
        ----------
        DetectorResponse: itkImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetDetectorResponse(self, DetectorResponse)

    def GetDetectorResponse(self):
        r"""GetDetectorResponse(self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetDetectorResponse(self)

    def SetMaterialAttenuations(self, MaterialAttenuations):
        r"""
        SetMaterialAttenuations(self, MaterialAttenuations)

        Parameters
        ----------
        MaterialAttenuations: itkImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetMaterialAttenuations(self, MaterialAttenuations)

    def GetMaterialAttenuations(self):
        r"""GetMaterialAttenuations(self) -> itkImageF2_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetMaterialAttenuations(self)

    def SetInputIncidentSpectrum(self, *args):
        r"""
        SetInputIncidentSpectrum(self, IncidentSpectrum)

        Parameters
        ----------
        IncidentSpectrum: itkImageF3 const *

        SetInputIncidentSpectrum(self, IncidentSpectrum)

        Parameters
        ----------
        IncidentSpectrum: itkVectorImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetInputIncidentSpectrum(self, *args)

    def SetInputSecondIncidentSpectrum(self, *args):
        r"""
        SetInputSecondIncidentSpectrum(self, SecondIncidentSpectrum)

        Parameters
        ----------
        SecondIncidentSpectrum: itkImageF3 const *

        SetInputSecondIncidentSpectrum(self, SecondIncidentSpectrum)

        Parameters
        ----------
        SecondIncidentSpectrum: itkVectorImageF2 const *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetInputSecondIncidentSpectrum(self, *args)

    def GetInputIncidentSpectrum(self):
        r"""GetInputIncidentSpectrum(self) -> itkImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetInputIncidentSpectrum(self)

    def GetInputSecondIncidentSpectrum(self):
        r"""GetInputSecondIncidentSpectrum(self) -> itkImageF3_ConstPointer"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetInputSecondIncidentSpectrum(self)

    def GetNumberOfIterations(self):
        r"""GetNumberOfIterations(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetNumberOfIterations(self)

    def SetNumberOfIterations(self, _arg):
        r"""
        SetNumberOfIterations(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetNumberOfIterations(self, _arg)

    def SetNumberOfEnergies(self, _arg):
        r"""
        SetNumberOfEnergies(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetNumberOfEnergies(self, _arg)

    def GetNumberOfEnergies(self):
        r"""GetNumberOfEnergies(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetNumberOfEnergies(self)

    def SetNumberOfMaterials(self, _arg):
        r"""
        SetNumberOfMaterials(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetNumberOfMaterials(self, _arg)

    def GetNumberOfMaterials(self):
        r"""GetNumberOfMaterials(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetNumberOfMaterials(self)

    def SetOptimizeWithRestarts(self, _arg):
        r"""
        SetOptimizeWithRestarts(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetOptimizeWithRestarts(self, _arg)

    def GetOptimizeWithRestarts(self):
        r"""GetOptimizeWithRestarts(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetOptimizeWithRestarts(self)

    def SetThresholds(self, _arg):
        r"""
        SetThresholds(self, _arg)

        Parameters
        ----------
        _arg: itkVariableLengthVectorD

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetThresholds(self, _arg)

    def GetThresholds(self):
        r"""GetThresholds(self) -> itkVariableLengthVectorD"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetThresholds(self)

    def SetNumberOfSpectralBins(self, _arg):
        r"""
        SetNumberOfSpectralBins(self, _arg)

        Parameters
        ----------
        _arg: unsigned int

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetNumberOfSpectralBins(self, _arg)

    def GetNumberOfSpectralBins(self):
        r"""GetNumberOfSpectralBins(self) -> unsigned int"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetNumberOfSpectralBins(self)

    def SetOutputInverseCramerRaoLowerBound(self, _arg):
        r"""
        SetOutputInverseCramerRaoLowerBound(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetOutputInverseCramerRaoLowerBound(self, _arg)

    def GetOutputInverseCramerRaoLowerBound(self):
        r"""GetOutputInverseCramerRaoLowerBound(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetOutputInverseCramerRaoLowerBound(self)

    def SetOutputFischerMatrix(self, _arg):
        r"""
        SetOutputFischerMatrix(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetOutputFischerMatrix(self, _arg)

    def GetOutputFischerMatrix(self):
        r"""GetOutputFischerMatrix(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetOutputFischerMatrix(self)

    def SetLogTransformEachBin(self, _arg):
        r"""
        SetLogTransformEachBin(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetLogTransformEachBin(self, _arg)

    def GetLogTransformEachBin(self):
        r"""GetLogTransformEachBin(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetLogTransformEachBin(self)

    def SetGuessInitialization(self, _arg):
        r"""
        SetGuessInitialization(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetGuessInitialization(self, _arg)

    def GetGuessInitialization(self):
        r"""GetGuessInitialization(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetGuessInitialization(self)

    def SetIsSpectralCT(self, _arg):
        r"""
        SetIsSpectralCT(self, _arg)

        Parameters
        ----------
        _arg: bool

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_SetIsSpectralCT(self, _arg)

    def GetIsSpectralCT(self):
        r"""GetIsSpectralCT(self) -> bool"""
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_GetIsSpectralCT(self)
    __swig_destroy__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.delete_rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2

    @staticmethod
    def cast(obj):
        r"""
        cast(obj) -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2

        Parameters
        ----------
        obj: itkLightObject *

        """
        return _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_cast(obj)

    def New(*args, **kargs):
        """New() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2

        Create a new object of the class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2 in _rtkSimplexSpectralProjectionsDecompositionImageFilterPython:
_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2_swigregister(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3IF3IF2IF2)

from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def simplex_spectral_projections_decomposition_image_filter(*args: itkt.ImageLike,  input_decomposed_projections: itkt.ImageBase=..., input_measured_projections: itkt.ImageBase=..., detector_response: itkt.Image=..., material_attenuations: itkt.Image=..., input_incident_spectrum: Union[itkt.VectorImage, itkt.Image]=..., input_second_incident_spectrum: Union[itkt.VectorImage, itkt.Image]=..., number_of_iterations: int=..., number_of_energies: int=..., number_of_materials: int=..., optimize_with_restarts: bool=..., thresholds=..., number_of_spectral_bins: int=..., output_inverse_cramer_rao_lower_bound: bool=..., output_fischer_matrix: bool=..., log_transform_each_bin: bool=..., guess_initialization: bool=..., is_spectral_ct: bool=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for SimplexSpectralProjectionsDecompositionImageFilter"""
    import itk

    kwarg_typehints = { 'input_decomposed_projections':input_decomposed_projections,'input_measured_projections':input_measured_projections,'detector_response':detector_response,'material_attenuations':material_attenuations,'input_incident_spectrum':input_incident_spectrum,'input_second_incident_spectrum':input_second_incident_spectrum,'number_of_iterations':number_of_iterations,'number_of_energies':number_of_energies,'number_of_materials':number_of_materials,'optimize_with_restarts':optimize_with_restarts,'thresholds':thresholds,'number_of_spectral_bins':number_of_spectral_bins,'output_inverse_cramer_rao_lower_bound':output_inverse_cramer_rao_lower_bound,'output_fischer_matrix':output_fischer_matrix,'log_transform_each_bin':log_transform_each_bin,'guess_initialization':guess_initialization,'is_spectral_ct':is_spectral_ct }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.SimplexSpectralProjectionsDecompositionImageFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def simplex_spectral_projections_decomposition_image_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.RTK.SimplexSpectralProjectionsDecompositionImageFilter
    simplex_spectral_projections_decomposition_image_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    simplex_spectral_projections_decomposition_image_filter.__doc__ = filter_object.__doc__



