DEFAULT_AZURE_API_KEY_NAME = "AZURE_API_KEY"
LITE_LLM_API_BASE_FIELD = "api_base"
LITE_LLM_API_KEY_FIELD = "api_key"
LITE_LLM_API_VERSION_FIELD = "api_version"
LITE_LLM_MODEL_FIELD = "model"
LITE_LLM_AZURE_AD_TOKEN = "azure_ad_token"

# Enable or disable Langfuse integration
RASA_LANGFUSE_INTEGRATION_ENABLED_ENV_VAR = "RASA_LANGFUSE_INTEGRATION_ENABLED"
# Langfuse configuration
LANGFUSE_CALLBACK_NAME = "langfuse"
LANGFUSE_HOST_ENV_VAR = "LANGFUSE_HOST"
LANGFUSE_PROJECT_ID_ENV_VAR = "LANGFUSE_PROJECT_ID"
LANGFUSE_PUBLIC_KEY_ENV_VAR = "LANGFUSE_PUBLIC_KEY"
LANGFUSE_SECRET_KEY_ENV_VAR = "LANGFUSE_SECRET_KEY"
