import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_aa425b4329(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_68ffa1f0b7():spartaqube_cli.list()
@app.command()
def sparta_0f2a84d09a():spartaqube_cli.sparta_0f2a84d09a()
@app.command()
def sparta_4267d3855d():print('Hello world!')
if __name__=='__main__':app()