import gradio as gr

def create_basic_template() -> gr.Blocks: ...
def create_tts_template() -> gr.Blocks: ...
def create_midi_generation_template() -> gr.Blocks: ...
def create_audio_analysis_template() -> gr.Blocks: ...
def create_paper_figure_template() -> gr.Blocks: ...
def create_all_templates() -> gr.Blocks: ...
