def test_markdown_class() -> None: ...
def test_markdown_class_no_data() -> None: ...
def test_markdown_stream(capsys) -> None: ...
def test_recursive_read(tmp_path) -> None: ...
def test_is_valid_url() -> None: ...
def test_cli_web_content(mocker) -> None: ...
def test_html_to_markdown_with_depth() -> None: ...
def test_display_markdown_hierarchically(capsys) -> None: ...
def runner(): ...
def test_cli_docs_no_docstring(runner, tmp_path) -> None: ...
def test_generate_docs(tmp_path) -> None: ...
def test_cli_docs_with_docstring(runner, tmp_path) -> None: ...
def test_cli_docs_with_directory(runner, tmp_path) -> None: ...
def test_cli_docs_with_package(runner, tmp_path) -> None: ...
def test_cli_no_input(runner) -> None: ...
def test_cli_help_option(runner) -> None: ...
