# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/nav_msgs/msg/occupancy_grid.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.nav_msgs.msg import map_meta_data_pb2 as make87__messages__ros2_dot_humble_dot_nav__msgs_dot_msg_dot_map__meta__data__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=make87_messages_ros2/humble/nav_msgs/msg/occupancy_grid.proto\x12(make87_messages_ros2.humble.nav_msgs.msg\x1a!make87_messages/core/header.proto\x1a<make87_messages_ros2/humble/nav_msgs/msg/map_meta_data.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\xd7\x01\n\rOccupancyGrid\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12\x43\n\x04info\x18\x03 \x01(\x0b\x32\x35.make87_messages_ros2.humble.nav_msgs.msg.MapMetaData\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.nav_msgs.msg.occupancy_grid_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_OCCUPANCYGRID']._serialized_start=260
  _globals['_OCCUPANCYGRID']._serialized_end=475
# @@protoc_insertion_point(module_scope)
