# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/delphi_mrr_msgs/msg/mrr_control_msg_fr.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.rolling.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_rolling_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nImake87_messages_ros2/rolling/delphi_mrr_msgs/msg/mrr_control_msg_fr.proto\x12\x30make87_messages_ros2.rolling.delphi_mrr_msgs.msg\x1a\x36make87_messages_ros2/rolling/std_msgs/msg/header.proto\"\xbe\x02\n\x0fMrrControlMsgFR\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.make87_messages_ros2.rolling.std_msgs.msg.Header\x12&\n\x1e\x63\x61n_sensitivity_profile_select\x18\x02 \x01(\r\x12\x1f\n\x17\x63\x61n_stop_frequency_frml\x18\x03 \x01(\r\x12\x1f\n\x17\x63\x61n_stop_frequency_frll\x18\x04 \x01(\r\x12\x1b\n\x13\x63\x61n_prp_factor_frml\x18\x05 \x01(\x02\x12\x1b\n\x13\x63\x61n_prp_factor_frll\x18\x06 \x01(\x02\x12!\n\x19\x63\x61n_desired_sweep_bw_frml\x18\x07 \x01(\r\x12!\n\x19\x63\x61n_desired_sweep_bw_frll\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.delphi_mrr_msgs.msg.mrr_control_msg_fr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MRRCONTROLMSGFR']._serialized_start=184
  _globals['_MRRCONTROLMSGFR']._serialized_end=502
# @@protoc_insertion_point(module_scope)
