# coding: utf-8

"""
    Autoenhance API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from autoenhance.models.order_in import OrderIn

class TestOrderIn(unittest.TestCase):
    """OrderIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderIn:
        """Test OrderIn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderIn`
        """
        model = OrderIn()
        if include_optional:
            return OrderIn(
                name = '',
                order_id = ''
            )
        else:
            return OrderIn(
        )
        """

    def testOrderIn(self):
        """Test OrderIn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
