
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-06-10T10:34:44-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "39feb5dd813bd7fcfd7d0b287685e8d0c6a7df08",
 "version": "0.13.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
