# GRPC Pipe
ARG_GRPC_CHANNEL = 'grpc_channel'

ARG_DEV = 'dev'
ARG_PROD = 'prod'
ARG_COMMAND = 'command'
ARG_ARGUMENT = 'argument'
ARG_RESPONSE = 'response'
ARG_USER = 'user'
ARG_KEY = 'key'
ARG_PATH = 'path'
ARG_NAME = 'name'
ARG_OUTPUT = 'output'
ARG_HASH = 'hash'
ARG_SOURCE = 'source'
ARG_TARGET = 'target'
ARG_COLLIDER = 'collider'
ARG_OUTPUT = 'output'

ARG_REG = 'reg'
ARG_MODE = 'mode'
ARG_OPEN = 'open'
ARG_TEMPLATE = 'template'
ARG_CONTAINER = 'container'
ARG_BUTTON = 'button'

ARG_ROOT = 'root'
ARG_COUNT = 'count'
ARG_GUID = 'guid'
