# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/novatel_gps_msgs/msg/inscov.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.rolling.novatel_gps_msgs.msg import novatel_message_header_pb2 as make87__messages__ros2_dot_rolling_dot_novatel__gps__msgs_dot_msg_dot_novatel__message__header__pb2
from make87_messages_ros2.rolling.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_rolling_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>make87_messages_ros2/rolling/novatel_gps_msgs/msg/inscov.proto\x12\x31make87_messages_ros2.rolling.novatel_gps_msgs.msg\x1aNmake87_messages_ros2/rolling/novatel_gps_msgs/msg/novatel_message_header.proto\x1a\x36make87_messages_ros2/rolling/std_msgs/msg/header.proto\"\xa6\x02\n\x06Inscov\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.make87_messages_ros2.rolling.std_msgs.msg.Header\x12\x63\n\x12novatel_msg_header\x18\x02 \x01(\x0b\x32G.make87_messages_ros2.rolling.novatel_gps_msgs.msg.NovatelMessageHeader\x12\x0c\n\x04week\x18\x03 \x01(\r\x12\x0f\n\x07seconds\x18\x04 \x01(\x01\x12\x1b\n\x13position_covariance\x18\x05 \x03(\x01\x12\x1b\n\x13\x61ttitude_covariance\x18\x06 \x03(\x01\x12\x1b\n\x13velocity_covariance\x18\x07 \x03(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.novatel_gps_msgs.msg.inscov_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSCOV']._serialized_start=254
  _globals['_INSCOV']._serialized_end=548
# @@protoc_insertion_point(module_scope)
