# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/aruco_opencv_msgs/msg/aruco_detection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.aruco_opencv_msgs.msg import board_pose_pb2 as make87__messages__ros2_dot_jazzy_dot_aruco__opencv__msgs_dot_msg_dot_board__pose__pb2
from make87_messages_ros2.jazzy.aruco_opencv_msgs.msg import marker_pose_pb2 as make87__messages__ros2_dot_jazzy_dot_aruco__opencv__msgs_dot_msg_dot_marker__pose__pb2
from make87_messages_ros2.jazzy.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_jazzy_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/jazzy/aruco_opencv_msgs/msg/aruco_detection.proto\x12\x30make87_messages_ros2.jazzy.aruco_opencv_msgs.msg\x1a\x41make87_messages_ros2/jazzy/aruco_opencv_msgs/msg/board_pose.proto\x1a\x42make87_messages_ros2/jazzy/aruco_opencv_msgs/msg/marker_pose.proto\x1a\x34make87_messages_ros2/jazzy/std_msgs/msg/header.proto\"\xed\x01\n\x0e\x41rucoDetection\x12?\n\x06header\x18\x01 \x01(\x0b\x32/.make87_messages_ros2.jazzy.std_msgs.msg.Header\x12M\n\x07markers\x18\x02 \x03(\x0b\x32<.make87_messages_ros2.jazzy.aruco_opencv_msgs.msg.MarkerPose\x12K\n\x06\x62oards\x18\x03 \x03(\x0b\x32;.make87_messages_ros2.jazzy.aruco_opencv_msgs.msg.BoardPoseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.aruco_opencv_msgs.msg.aruco_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ARUCODETECTION']._serialized_start=314
  _globals['_ARUCODETECTION']._serialized_end=551
# @@protoc_insertion_point(module_scope)
