# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/sat_info.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import sat_flags_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_sat__flags__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/sat_info.proto\x12-make87_messages_ros2.jazzy.ublox_ubx_msgs.msg\x1a=make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/sat_flags.proto\"\xaa\x01\n\x07SatInfo\x12\x0f\n\x07gnss_id\x18\x01 \x01(\r\x12\r\n\x05sv_id\x18\x02 \x01(\r\x12\x0b\n\x03\x63no\x18\x03 \x01(\r\x12\x0c\n\x04\x65lev\x18\x04 \x01(\x05\x12\x0c\n\x04\x61zim\x18\x05 \x01(\x05\x12\x0e\n\x06pr_res\x18\x06 \x01(\x05\x12\x46\n\x05\x66lags\x18\x07 \x01(\x0b\x32\x37.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.SatFlagsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.sat_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SATINFO']._serialized_start=175
  _globals['_SATINFO']._serialized_end=345
# @@protoc_insertion_point(module_scope)
