# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/rmf_traffic_msgs/msg/traffic_dependency.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nImake87_messages_ros2/humble/rmf_traffic_msgs/msg/traffic_dependency.proto\x12\x30make87_messages_ros2.humble.rmf_traffic_msgs.msg\x1a!make87_messages/core/header.proto\"\xb1\x01\n\x11TrafficDependency\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x1c\n\x14\x64\x65pendent_checkpoint\x18\x02 \x01(\x04\x12\x16\n\x0eon_participant\x18\x03 \x01(\x04\x12\x0f\n\x07on_plan\x18\x04 \x01(\x04\x12\x10\n\x08on_route\x18\x05 \x01(\x04\x12\x15\n\ron_checkpoint\x18\x06 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.rmf_traffic_msgs.msg.traffic_dependency_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TRAFFICDEPENDENCY']._serialized_start=163
  _globals['_TRAFFICDEPENDENCY']._serialized_end=340
# @@protoc_insertion_point(module_scope)
