# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/octomap_msgs/srv/get_octomap.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/octomap_msgs/srv/get_octomap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.octomap_msgs.msg import octomap_pb2 as make87__messages__ros2_dot_jazzy_dot_octomap__msgs_dot_msg_dot_octomap__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=make87_messages_ros2/jazzy/octomap_msgs/srv/get_octomap.proto\x12+make87_messages_ros2.jazzy.octomap_msgs.srv\x1a\x39make87_messages_ros2/jazzy/octomap_msgs/msg/octomap.proto\"\x13\n\x11GetOctomapRequest\"W\n\x12GetOctomapResponse\x12\x41\n\x03map\x18\x01 \x01(\x0b\x32\x34.make87_messages_ros2.jazzy.octomap_msgs.msg.Octomapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.octomap_msgs.srv.get_octomap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETOCTOMAPREQUEST']._serialized_start=169
  _globals['_GETOCTOMAPREQUEST']._serialized_end=188
  _globals['_GETOCTOMAPRESPONSE']._serialized_start=190
  _globals['_GETOCTOMAPRESPONSE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
