# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/marine_acoustic_msgs/msg/sonar_ranges.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.geometry_msgs.msg import vector3_pb2 as make87__messages__ros2_dot_humble_dot_geometry__msgs_dot_msg_dot_vector3__pb2
from make87_messages_ros2.humble.marine_acoustic_msgs.msg import detection_flag_pb2 as make87__messages__ros2_dot_humble_dot_marine__acoustic__msgs_dot_msg_dot_detection__flag__pb2
from make87_messages_ros2.humble.marine_acoustic_msgs.msg import ping_info_pb2 as make87__messages__ros2_dot_humble_dot_marine__acoustic__msgs_dot_msg_dot_ping__info__pb2
from make87_messages_ros2.humble.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_humble_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGmake87_messages_ros2/humble/marine_acoustic_msgs/msg/sonar_ranges.proto\x12\x34make87_messages_ros2.humble.marine_acoustic_msgs.msg\x1a!make87_messages/core/header.proto\x1a;make87_messages_ros2/humble/geometry_msgs/msg/vector3.proto\x1aImake87_messages_ros2/humble/marine_acoustic_msgs/msg/detection_flag.proto\x1a\x44make87_messages_ros2/humble/marine_acoustic_msgs/msg/ping_info.proto\x1a\x35make87_messages_ros2/humble/std_msgs/msg/header.proto\"\xb6\x03\n\x0bSonarRanges\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x45\n\x0bros2_header\x18\x02 \x01(\x0b\x32\x30.make87_messages_ros2.humble.std_msgs.msg.Header\x12Q\n\tping_info\x18\x03 \x01(\x0b\x32>.make87_messages_ros2.humble.marine_acoustic_msgs.msg.PingInfo\x12R\n\x05\x66lags\x18\x04 \x03(\x0b\x32\x43.make87_messages_ros2.humble.marine_acoustic_msgs.msg.DetectionFlag\x12\x17\n\x0ftransmit_delays\x18\x05 \x03(\x02\x12\x13\n\x0bintensities\x18\x06 \x03(\x02\x12M\n\rbeam_unit_vec\x18\x07 \x03(\x0b\x32\x36.make87_messages_ros2.humble.geometry_msgs.msg.Vector3\x12\x0e\n\x06ranges\x18\x08 \x03(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.marine_acoustic_msgs.msg.sonar_ranges_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONARRANGES']._serialized_start=426
  _globals['_SONARRANGES']._serialized_end=864
# @@protoc_insertion_point(module_scope)
