# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/gc_spl_interfaces/msg/robot_info14.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCmake87_messages_ros2/jazzy/gc_spl_interfaces/msg/robot_info14.proto\x12\x30make87_messages_ros2.jazzy.gc_spl_interfaces.msg\"=\n\x0bRobotInfo14\x12\x0f\n\x07penalty\x18\x01 \x01(\r\x12\x1d\n\x15secs_till_unpenalised\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.gc_spl_interfaces.msg.robot_info14_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ROBOTINFO14']._serialized_start=121
  _globals['_ROBOTINFO14']._serialized_end=182
# @@protoc_insertion_point(module_scope)
