# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/humble/vimbax_camera_msgs/srv/status.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/humble/vimbax_camera_msgs/srv/status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.vimbax_camera_msgs.msg import error_pb2 as make87__messages__ros2_dot_humble_dot_vimbax__camera__msgs_dot_msg_dot_error__pb2
from make87_messages_ros2.humble.vimbax_camera_msgs.msg import trigger_info_pb2 as make87__messages__ros2_dot_humble_dot_vimbax__camera__msgs_dot_msg_dot_trigger__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?make87_messages_ros2/humble/vimbax_camera_msgs/srv/status.proto\x12\x32make87_messages_ros2.humble.vimbax_camera_msgs.srv\x1a!make87_messages/core/header.proto\x1a>make87_messages_ros2/humble/vimbax_camera_msgs/msg/error.proto\x1a\x45make87_messages_ros2/humble/vimbax_camera_msgs/msg/trigger_info.proto\"=\n\rStatusRequest\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\"\xaa\x04\n\x0eStatusResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12H\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x39.make87_messages_ros2.humble.vimbax_camera_msgs.msg.Error\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x12\n\nmodel_name\x18\x04 \x01(\t\x12\x1f\n\x17\x64\x65vice_firmware_version\x18\x05 \x01(\t\x12\x11\n\tdevice_id\x18\x06 \x01(\t\x12\x16\n\x0e\x64\x65vice_user_id\x18\x07 \x01(\t\x12\x1c\n\x14\x64\x65vice_serial_number\x18\x08 \x01(\t\x12\x14\n\x0cinterface_id\x18\t \x01(\t\x12\x1a\n\x12transport_layer_id\x18\n \x01(\t\x12\x11\n\tstreaming\x18\x0b \x01(\x08\x12\r\n\x05width\x18\x0c \x01(\r\x12\x0e\n\x06height\x18\r \x01(\r\x12\x12\n\nframe_rate\x18\x0e \x01(\x01\x12\x14\n\x0cpixel_format\x18\x0f \x01(\t\x12U\n\x0ctrigger_info\x18\x10 \x03(\x0b\x32?.make87_messages_ros2.humble.vimbax_camera_msgs.msg.TriggerInfo\x12\x12\n\nip_address\x18\x11 \x01(\t\x12\x13\n\x0bmac_address\x18\x12 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.vimbax_camera_msgs.srv.status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=289
  _globals['_STATUSREQUEST']._serialized_end=350
  _globals['_STATUSRESPONSE']._serialized_start=353
  _globals['_STATUSRESPONSE']._serialized_end=907
# @@protoc_insertion_point(module_scope)
