from typing import Dict, List, Tuple, Union
import ctypes

def count() -> int: ...
def get_prop(device_id:int=0) -> Dict: ...
def tocuda(pyobject:Union[ctypes.c_void_p,List], device_id:int, numel:int, fmt:str) -> ctypes.c_void_p: ...
def tocpu(pyobject, numel:int, fmt:str) -> ctypes.c_void_p: ...

def get_device_name(device:int) -> str: ...
def current_device() -> int: ...
def get_arch_list() -> List[Tuple[int,int]]: ...
