# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/robot_localization/srv/set_utm_zone.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/rolling/robot_localization/srv/set_utm_zone.proto\x12\x33make87_messages_ros2.rolling.robot_localization.srv\"%\n\x11SetUTMZoneRequest\x12\x10\n\x08utm_zone\x18\x01 \x01(\t\"\x14\n\x12SetUTMZoneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.robot_localization.srv.set_utm_zone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETUTMZONEREQUEST']._serialized_start=127
  _globals['_SETUTMZONEREQUEST']._serialized_end=164
  _globals['_SETUTMZONERESPONSE']._serialized_start=166
  _globals['_SETUTMZONERESPONSE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
