# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/humble/play_motion2_msgs/srv/is_motion_ready.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGmake87_messages_ros2/humble/play_motion2_msgs/srv/is_motion_ready.proto\x12\x31make87_messages_ros2.humble.play_motion2_msgs.srv\x1a!make87_messages/core/header.proto\"X\n\x14IsMotionReadyRequest\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x12\n\nmotion_key\x18\x02 \x01(\t\"W\n\x15IsMotionReadyResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12\x10\n\x08is_ready\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.play_motion2_msgs.srv.is_motion_ready_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISMOTIONREADYREQUEST']._serialized_start=161
  _globals['_ISMOTIONREADYREQUEST']._serialized_end=249
  _globals['_ISMOTIONREADYRESPONSE']._serialized_start=251
  _globals['_ISMOTIONREADYRESPONSE']._serialized_end=338
# @@protoc_insertion_point(module_scope)
