location_code_prefix = {
    # A – Châu Phi
    'DA': 'Algeria',
    'DB': 'Benin',
    'DF': 'Burkina Faso',
    'DG': 'Ghana',
    'DI': 'Côte d\'Ivoire',
    'DN': 'Nigeria',
    'DR': 'Niger',
    'DT': 'Tunisia',
    'DX': 'Togo',
    # E – Bắc Âu
    'EB': 'Belgium',
    'ED': 'Germany',
    'EE': 'Estonia',
    'EF': 'Finland',
    'EG': 'United Kingdom',
    'EH': 'Netherlands',
    'EI': 'Ireland',
    'EK': 'Denmark',
    'EL': 'Luxembourg',
    'EN': 'Norway',
    'EP': 'Poland',
    'ES': 'Sweden',
    'ET': 'Germany (military)',
    'EV': 'Latvia',
    'EY': 'Lithuania',
    # L – Nam Âu
    'LA': 'Albania',
    'LB': 'Bulgaria',
    'LC': 'Cyprus',
    'LD': 'Croatia',
    'LE': 'Spain',
    'LF': 'France',
    'LG': 'Greece',
    'LH': 'Hungary',
    'LI': 'Italy',
    'LJ': 'Slovenia',
    'LK': 'Czech Republic',
    'LL': 'Israel',
    'LM': 'Malta',
    'LN': 'Monaco',
    'LO': 'Austria',
    'LP': 'Portugal',
    'LQ': 'Bosnia and Herzegovina',
    'LR': 'Romania',
    'LS': 'Switzerland',
    'LT': 'Turkey',
    'LU': 'Moldova',
    'LV': 'Vatican City',
    'LW': 'North Macedonia',
    'LX': 'Gibraltar',
    'LY': 'Serbia and Montenegro',
    'LZ': 'Slovakia',
    # M – Trung Mỹ
    'MB': 'Bahamas',
    'MD': 'Dominican Republic',
    'MG': 'Guatemala',
    'MH': 'Honduras',
    'MK': 'Jamaica',
    'MM': 'Mexico',
    'MN': 'Nicaragua',
    'MP': 'Panama',
    'MR': 'Costa Rica',
    'MS': 'El Salvador',
    'MT': 'Haiti',
    'MU': 'Cuba',
    'MW': 'Cayman Islands',
    'MY': 'Bahamas',
    'MZ': 'Belize',
    # O – Trung Đông
    'OA': 'Afghanistan',
    'OB': 'Bahrain',
    'OE': 'Saudi Arabia',
    'OI': 'Iran',
    'OJ': 'Jordan',
    'OK': 'Kuwait',
    'OL': 'Lebanon',
    'OM': 'United Arab Emirates',
    'OO': 'Oman',
    'OP': 'Pakistan',
    'OR': 'Iraq',
    'OS': 'Syria',
    'OT': 'Qatar',
    'OY': 'Yemen',
    # R – Đông Á
    'RC': 'Taiwan',
    'RJ': 'Japan',
    'RK': 'South Korea',
    'RO': 'Japan (Okinawa)',
    'RP': 'Philippines',
    'RR': 'Russia (Far East)',
    # S – Nam Mỹ
    'SA': 'Argentina',
    'SB': 'Brazil',
    'SC': 'Chile',
    'SD': 'Brazil',
    'SE': 'Ecuador',
    'SG': 'Paraguay',
    'SK': 'Colombia',
    'SL': 'Bolivia',
    'SM': 'Suriname',
    'SN': 'Brazil',
    'SO': 'French Guiana',
    'SP': 'Peru',
    'SU': 'Uruguay',
    'SV': 'Venezuela',
    'SW': 'Brazil',
    'SY': 'Guyana',
    'SZ': 'Brazil',
    # T – Caribbean
    'TA': 'Antigua and Barbuda',
    'TB': 'Barbados',
    'TD': 'Dominica',
    'TF': 'Guadeloupe',
    'TG': 'Grenada',
    'TI': 'U.S. Virgin Islands',
    'TJ': 'Puerto Rico',
    'TK': 'Saint Kitts and Nevis',
    'TL': 'Saint Lucia',
    'TN': 'Netherlands Antilles',
    'TQ': 'Anguilla',
    'TR': 'Montserrat',
    'TT': 'Trinidad and Tobago',
    'TU': 'British Virgin Islands',
    'TV': 'Saint Vincent and the Grenadines',
    'TX': 'Bermuda',
    # U – Nga và các nước lân cận
    'UA': 'Kazakhstan',
    'UB': 'Azerbaijan',
    'UC': 'Kyrgyzstan',
    'UD': 'Armenia',
    'UG': 'Georgia',
    'UK': 'Ukraine',
    'UM': 'Belarus',
    'UT': 'Tajikistan, Turkmenistan, Uzbekistan',
    'UU': 'Russia (Moscow region)',
    'UW': 'Russia (Volga region)',
    'UX': 'Russia (Central Siberia)',
    # V – Nam Á và Đông Nam Á
    'VA': 'India (West)',
    'VC': 'Sri Lanka',
    'VD': 'Cambodia',
    'VE': 'India (East)',
    'VG': 'Bangladesh',
    'VH': 'Hong Kong',
    'VI': 'India (North)',
    'VL': 'Laos',
    'VM': 'Macau',
    'VN': 'Nepal',
    'VO': 'India (South)',
    'VQ': 'Bhutan',
    'VR': 'Maldives',
    'VT': 'Thailand',
    'VV': 'Vietnam',
    'VY': 'Myanmar',
    # W – Đông Nam Á biển
    'WA': 'Indonesia',
    'WB': 'Brunei, Malaysia (East)',
    'WI': 'Indonesia',
    'WM': 'Malaysia (Peninsular)',
    'WP': 'Timor-Leste',
    'WS': 'Singapore',
    # Y – Úc
    'Y': 'Australia',
    # Z – Trung Quốc, Bắc Triều Tiên và Mông Cổ
    'ZB': 'China (North)',
    'ZG': 'China (South)',
    'ZH': 'China (Central)',
    'ZK': 'North Korea',
    'ZM': 'Mongolia',
    'ZS': 'China (East)',
    'ZU': 'China (Southwest)',
    'ZW': 'China (Northwest)',
    'ZY': 'China (Northeast)',
}
