entity = {
    # AGA - Aerodromes - Lighting facilities (L)
    'LA': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Approach lighting system'},
    'LB': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Aerodrome beacon'},
    'LC': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Runway centre line lights'},
    'LD': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Landing direction indicator lights'},
    'LE': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Runway edge lights'},
    'LF': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Sequenced flashing lights'},
    'LG': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Pilot-controlled lighting'},
    'LH': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'High intensity runway lights'},
    'LI': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Runway end identifier lights'},
    'LJ': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Runway alignment indicator lights'},
    'LK': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Category II components of approach lighting system'},
    'LL': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Low intensity runway lights'},
    'LM': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Medium intensity runway lights'},
    'LP': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Precision approach path indicator'},
    'LR': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'All landing area lighting facilities'},
    'LS': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Stopway lights'},
    'LT': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Threshold lights'},
    'LU': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Helicopter approach path indicator'},
    'LV': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Visual approach slope indicator system'},
    'LW': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Heliport lighting'},
    'LX': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Taxiway centre line lights'},
    'LY': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Taxiway edge lights'},
    'LZ': {'area': 'AGA', 'sub_area': 'Lighting facilities', 'subject': 'Runway touchdown zone lights'},

    # AGA - Aerodromes - Movement and landing area (M)
    'MA': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Movement area'},
    'MB': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Bearing strength'},
    'MC': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Clearway'},
    'MD': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Declared distances'},
    'MG': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Taxiing guidance system'},
    'MH': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Runway arresting gear'},
    'MK': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Parking area'},
    'MM': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Daylight markings'},
    'MN': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Apron'},
    'MO': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Stopbar'},
    'MP': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Aircraft stands'},
    'MR': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Runway'},
    'MS': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Stopway'},
    'MT': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Threshold'},
    'MU': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Runway turning bay'},
    'MW': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Strip/shoulder'},
    'MX': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Taxiway(s)'},
    'MY': {'area': 'AGA', 'sub_area': 'Movement and landing area', 'subject': 'Rapid exit taxiway'},

    # AGA - Aerodromes - Facilities and services (F)
    'FA': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Aerodrome'},
    'FB': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Friction measuring device'},
    'FC': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Ceiling measurement equipment'},
    'FD': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Docking system'},
    'FE': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Oxygen'},
    'FF': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Firefighting and rescue'},
    'FG': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Ground movement control'},
    'FH': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Helicopter alighting area/platform'},
    'FI': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Aircraft de-icing'},
    'FJ': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Oils'},
    'FL': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Landing direction indicator'},
    'FM': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Meteorological service'},
    'FO': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Fog dispersal system'},
    'FP': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Heliport'},
    'FS': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Snow removal equipment'},
    'FT': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Transmissometer'},
    'FU': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Fuel availability'},
    'FW': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Wind direction indicator'},
    'FZ': {'area': 'AGA', 'sub_area': 'Facilities and services', 'subject': 'Customs/immigration'},

    # ATM - Air Traffic Management - Airspace organization management (A)
    'AA': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Minimum altitude'},
    'AC': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Control zone'},
    'AD': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Air defence identification zone'},
    'AE': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Control area'},
    'AF': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Flight information region'},
    'AH': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Upper control area'},
    'AL': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Minimum usable flight level'},
    'AN': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Area navigation route'},
    'AO': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Oceanic control area'},
    'AP': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Reporting point'},
    'AR': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'ATS route'},
    'AT': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Terminal control area'},
    'AU': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Upper flight information region'},
    'AV': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Upper advisory area'},
    'AX': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Significant point'},
    'AZ': {'area': 'ATM', 'sub_area': 'Airspace organization management', 'subject': 'Aerodrome traffic zone'},

    # ATM - Air Traffic Management - Air traffic and VOLMET services (S)
    'SA': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Automatic terminal information service'},
    'SB': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'ATS reporting office'},
    'SC': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Area control centre'},
    'SE': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Flight information service'},
    'SF': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Aerodrome flight information service'},
    'SL': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Flow control centre'},
    'SO': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Oceanic area control centre'},
    'SP': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Approach control service'},
    'SS': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Flight service station'},
    'ST': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Aerodrome control tower'},
    'SU': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Upper area control centre'},
    'SV': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'VOLMET broadcast'},
    'SY': {'area': 'ATM', 'sub_area': 'Air traffic and VOLMET services', 'subject': 'Upper advisory service'},

    # ATM - Air Traffic Management - Air traffic procedures (P)
    'PA': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Standard instrument arrival'},
    'PB': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Standard VFR arrival'},
    'PC': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Contingency procedures'},
    'PD': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Standard instrument departure'},
    'PE': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Standard VFR departure'},
    'PF': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Flow control procedure'},
    'PH': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Holding procedure'},
    'PI': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Instrument approach procedure'},
    'PK': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'VFR approach procedure'},
    'PL': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Flight plan processing, filing and related contingency'},
    'PM': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Aerodrome operating minima'},
    'PN': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Noise operating restrictions'},
    'PO': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Obstacle clearance altitude and height'},
    'PR': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Radio failure procedure'},
    'PT': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Transition altitude or transition level'},
    'PU': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Missed approach procedure'},
    'PX': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'Minimum holding altitude'},
    'PZ': {'area': 'ATM', 'sub_area': 'Air traffic procedures', 'subject': 'ADIZ procedure'},

    # CNS - Communications and surveillance facilities (C)
    'CA': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Air/ground facility'},
    'CB': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Automatic dependent surveillance — broadcast'},
    'CC': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Automatic dependent surveillance — contract'},
    'CD': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Controller-pilot data link communications'},
    'CE': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'En-route surveillance radar'},
    'CG': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Ground controlled approach system'},
    'CL': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Selective calling system'},
    'CM': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Surface movement radar'},
    'CP': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Precision approach radar'},
    'CR': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Surveillance radar element of precision approach radar system'},
    'CS': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Secondary surveillance radar'},
    'CT': {'area': 'CNS', 'sub_area': 'Communications and surveillance facilities', 'subject': 'Terminal area surveillance radar'},

    # CNS - Instrument and microwave landing systems (I)
    'IC': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Instrument landing system'},
    'ID': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'DME associated with ILS'},
    'IG': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Glide path (ILS)'},
    'II': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Inner marker (ILS)'},
    'IL': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Localizer (ILS)'},
    'IM': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Middle marker (ILS)'},
    'IN': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Localizer (not associated with ILS)'},
    'IO': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Outer marker (ILS)'},
    'IS': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'ILS Category I'},
    'IT': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'ILS Category II'},
    'IU': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'ILS Category III'},
    'IW': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Microwave landing system'},
    'IX': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Locator, outer (ILS)'},
    'IY': {'area': 'CNS', 'sub_area': 'Instrument and microwave landing systems', 'subject': 'Locator, middle (ILS)'},

    # CNS - GNSS services (G)
    'GA': {'area': 'CNS', 'sub_area': 'GNSS services', 'subject': 'GNSS airfield-specific operations'},
    'GW': {'area': 'CNS', 'sub_area': 'GNSS services', 'subject': 'GNSS area-wide operations'},

    # CNS - Terminal and en-route navigation facilities (N)
    'NA': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'All radio navigation facilities'},
    'NB': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'Non-directional radio beacon'},
    'NC': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'DECCA'},
    'ND': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'Distance measuring equipment'},
    'NF': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'Fan marker'},
    'NL': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'Locator'},
    'NM': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'VOR/DME'},
    'NN': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'TACAN'},
    'NO': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'OMEGA'},
    'NT': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'VORTAC'},
    'NV': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'VOR'},
    'NX': {'area': 'CNS', 'sub_area': 'Terminal and en-route navigation facilities', 'subject': 'Direction-finding station'},

    # Navigation Warnings - Airspace restrictions (R)
    'RA': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Airspace reservation'},
    'RD': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Danger area'},
    'RM': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Military operating area'},
    'RO': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Overflying of'},
    'RP': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Prohibited area'},
    'RR': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Restricted area'},
    'RT': {'area': 'Navigation Warnings', 'sub_area': 'Airspace restrictions', 'subject': 'Temporary restricted area'},

    # Navigation Warnings - Warnings (W)
    'WA': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Air display'},
    'WB': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Aerobatics'},
    'WC': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Captive balloon or kite'},
    'WD': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Demolition of explosives'},
    'WE': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Exercises'},
    'WF': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Air refuelling'},
    'WG': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Glider flying'},
    'WH': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Blasting'},
    'WJ': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Banner/target towing'},
    'WL': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Ascent of free balloon'},
    'WM': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Missile, gun or rocket firing'},
    'WP': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Parachute jumping exercise, paragliding or hang gliding'},
    'WR': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Radioactive materials or toxic chemicals'},
    'WS': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Burning or blowing gas'},
    'WT': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Mass movement of aircraft'},
    'WU': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Unmanned aircraft'},
    'WV': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Formation flight'},
    'WW': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Significant volcanic activity'},
    'WY': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Aerial survey'},
    'WZ': {'area': 'Navigation Warnings', 'sub_area': 'Warnings', 'subject': 'Model flying'},

    # Other Information (O)
    'OA': {'area': 'Other Information', 'sub_area': 'Other Information', 'subject': 'Aeronautical information service'},
    'OB': {'area': 'Other Information', 'sub_area': 'Other Information', 'subject': 'Obstacle'},
    'OE': {'area': 'Other Information', 'sub_area': 'Other Information', 'subject': 'Aircraft entry requirements'},
    'OL': {'area': 'Other Information', 'sub_area': 'Other Information', 'subject': 'Obstacle lights'},
    'OR': {'area': 'Other Information', 'sub_area': 'Other Information', 'subject': 'Rescue coordination centre'}
}