# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/humble/autoware_control_msgs/msg/control_horizon.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/humble/autoware_control_msgs/msg/control_horizon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages.core import header_pb2 as make87__messages_dot_core_dot_header__pb2
from make87_messages_ros2.humble.autoware_control_msgs.msg import control_pb2 as make87__messages__ros2_dot_humble_dot_autoware__control__msgs_dot_msg_dot_control__pb2
from make87_messages_ros2.humble.builtin_interfaces.msg import time_pb2 as make87__messages__ros2_dot_humble_dot_builtin__interfaces_dot_msg_dot_time__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKmake87_messages_ros2/humble/autoware_control_msgs/msg/control_horizon.proto\x12\x35make87_messages_ros2.humble.autoware_control_msgs.msg\x1a!make87_messages/core/header.proto\x1a\x43make87_messages_ros2/humble/autoware_control_msgs/msg/control.proto\x1a=make87_messages_ros2/humble/builtin_interfaces/msg/time.proto\"\xbf\x02\n\x0e\x43ontrolHorizon\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.make87_messages.core.Header\x12G\n\x05stamp\x18\x02 \x01(\x0b\x32\x38.make87_messages_ros2.humble.builtin_interfaces.msg.Time\x12N\n\x0c\x63ontrol_time\x18\x03 \x01(\x0b\x32\x38.make87_messages_ros2.humble.builtin_interfaces.msg.Time\x12\x14\n\x0ctime_step_ms\x18\x04 \x01(\x02\x12P\n\x08\x63ontrols\x18\x05 \x03(\x0b\x32>.make87_messages_ros2.humble.autoware_control_msgs.msg.Controlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.humble.autoware_control_msgs.msg.control_horizon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLHORIZON']._serialized_start=302
  _globals['_CONTROLHORIZON']._serialized_end=621
# @@protoc_insertion_point(module_scope)
