# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/smacc2_msgs/msg/smacc_state_machine.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.smacc2_msgs.msg import smacc_state_pb2 as make87__messages__ros2_dot_jazzy_dot_smacc2__msgs_dot_msg_dot_smacc__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDmake87_messages_ros2/jazzy/smacc2_msgs/msg/smacc_state_machine.proto\x12*make87_messages_ros2.jazzy.smacc2_msgs.msg\x1a<make87_messages_ros2/jazzy/smacc2_msgs/msg/smacc_state.proto\"[\n\x11SmaccStateMachine\x12\x46\n\x06states\x18\x01 \x03(\x0b\x32\x36.make87_messages_ros2.jazzy.smacc2_msgs.msg.SmaccStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.smacc2_msgs.msg.smacc_state_machine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMACCSTATEMACHINE']._serialized_start=178
  _globals['_SMACCSTATEMACHINE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
