# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetProvidedResourcesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'intent_outputs': 'list[JsonNode]',
        'out_override': 'JsonNode'
    }

    attribute_map = {
        'intent_outputs': 'intentOutputs',
        'out_override': 'outOverride'
    }

    def __init__(self, intent_outputs=None, out_override=None):  # noqa: E501
        """GetProvidedResourcesResponse - a model defined in Swagger"""  # noqa: E501
        self._intent_outputs = None
        self._out_override = None
        self.discriminator = None
        if intent_outputs is not None:
            self.intent_outputs = intent_outputs
        if out_override is not None:
            self.out_override = out_override

    @property
    def intent_outputs(self):
        """Gets the intent_outputs of this GetProvidedResourcesResponse.  # noqa: E501


        :return: The intent_outputs of this GetProvidedResourcesResponse.  # noqa: E501
        :rtype: list[JsonNode]
        """
        return self._intent_outputs

    @intent_outputs.setter
    def intent_outputs(self, intent_outputs):
        """Sets the intent_outputs of this GetProvidedResourcesResponse.


        :param intent_outputs: The intent_outputs of this GetProvidedResourcesResponse.  # noqa: E501
        :type: list[JsonNode]
        """

        self._intent_outputs = intent_outputs

    @property
    def out_override(self):
        """Gets the out_override of this GetProvidedResourcesResponse.  # noqa: E501


        :return: The out_override of this GetProvidedResourcesResponse.  # noqa: E501
        :rtype: JsonNode
        """
        return self._out_override

    @out_override.setter
    def out_override(self, out_override):
        """Sets the out_override of this GetProvidedResourcesResponse.


        :param out_override: The out_override of this GetProvidedResourcesResponse.  # noqa: E501
        :type: JsonNode
        """

        self._out_override = out_override

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetProvidedResourcesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetProvidedResourcesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
