from mrender.md import Markdown as Markdown

def parse_google_docstring(docstring: str) -> dict[str, str | dict[str, str] | list[str]]: ...
def generate_feature_list(description: str) -> str: ...
def generate_examples(examples: list[str]) -> str: ...
def generate_docs(file_path_or_src: str | object, is_package: bool = False, depth: int = 2) -> str: ...
def main(path: str, output_file: str = None, *, use_regex: bool = False, stream: bool = False): ...
def cli(path: str, output_file: str = None) -> None: ...
