from types import ModuleType

def bfs_explore_module(module: ModuleType, depth: int = 1, include_signatures: bool = True, include_docstrings: bool = True, max_depth: int = 3) -> list[dict[str, str | dict]]: ...
def extract_docstring_from_object(obj: str | ModuleType | type | None, depth: int = 0, include_signatures: bool = True, include_docstrings: bool = True) -> list[dict[str, str | dict]]: ...
