from _typeshed import Incomplete
from types import TracebackType

class LivePanelDisplay:
    lines: Incomplete
    def __init__(self, msg: str | None = None) -> None: ...
    def update(self, msg: str, add_sleep: float | None = None) -> None: ...
    def __enter__(self) -> LivePanelDisplay: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
