"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from alph_sdk.types import BaseModel
from alph_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StartProjectRequestBodyTypedDict(TypedDict):
    environment: NotRequired[str]
    port: NotRequired[float]
    server_request: NotRequired[str]


class StartProjectRequestBody(BaseModel):
    environment: Optional[str] = None

    port: Optional[float] = None

    server_request: Optional[str] = None


class StartProjectRequestTypedDict(TypedDict):
    server_name: str
    request_body: NotRequired[StartProjectRequestBodyTypedDict]


class StartProjectRequest(BaseModel):
    server_name: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[StartProjectRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
