# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/rosapi_msgs/srv/get_ros_version.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/rosapi_msgs/srv/get_ros_version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@make87_messages_ros2/jazzy/rosapi_msgs/srv/get_ros_version.proto\x12*make87_messages_ros2.jazzy.rosapi_msgs.srv\"\x16\n\x14GetROSVersionRequest\"8\n\x15GetROSVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x0e\n\x06\x64istro\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.rosapi_msgs.srv.get_ros_version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETROSVERSIONREQUEST']._serialized_start=112
  _globals['_GETROSVERSIONREQUEST']._serialized_end=134
  _globals['_GETROSVERSIONRESPONSE']._serialized_start=136
  _globals['_GETROSVERSIONRESPONSE']._serialized_end=192
# @@protoc_insertion_point(module_scope)
