# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/ubx_nav_status.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/ubx_nav_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.jazzy.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_jazzy_dot_std__msgs_dot_msg_dot_header__pb2
from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import carr_soln_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_carr__soln__pb2
from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import gps_fix_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_gps__fix__pb2
from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import map_matching_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_map__matching__pb2
from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import psm_status_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_psm__status__pb2
from make87_messages_ros2.jazzy.ublox_ubx_msgs.msg import spoof_det_pb2 as make87__messages__ros2_dot_jazzy_dot_ublox__ubx__msgs_dot_msg_dot_spoof__det__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBmake87_messages_ros2/jazzy/ublox_ubx_msgs/msg/ubx_nav_status.proto\x12-make87_messages_ros2.jazzy.ublox_ubx_msgs.msg\x1a\x34make87_messages_ros2/jazzy/std_msgs/msg/header.proto\x1a=make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/carr_soln.proto\x1a;make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/gps_fix.proto\x1a@make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/map_matching.proto\x1a>make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/psm_status.proto\x1a=make87_messages_ros2/jazzy/ublox_ubx_msgs/msg/spoof_det.proto\"\xe7\x04\n\x0cUBXNavStatus\x12?\n\x06header\x18\x01 \x01(\x0b\x32/.make87_messages_ros2.jazzy.std_msgs.msg.Header\x12\x0c\n\x04itow\x18\x02 \x01(\r\x12\x46\n\x07gps_fix\x18\x03 \x01(\x0b\x32\x35.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.GpsFix\x12\x12\n\ngps_fix_ok\x18\x04 \x01(\x08\x12\x11\n\tdiff_soln\x18\x05 \x01(\x08\x12\x0f\n\x07wkn_set\x18\x06 \x01(\x08\x12\x0f\n\x07tow_set\x18\x07 \x01(\x08\x12\x11\n\tdiff_corr\x18\x08 \x01(\x08\x12\x17\n\x0f\x63\x61rr_soln_valid\x18\t \x01(\x08\x12P\n\x0cmap_matching\x18\n \x01(\x0b\x32:.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.MapMatching\x12\x45\n\x03psm\x18\x0b \x01(\x0b\x32\x38.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.PSMStatus\x12J\n\tspoof_det\x18\x0c \x01(\x0b\x32\x37.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.SpoofDet\x12J\n\tcarr_soln\x18\r \x01(\x0b\x32\x37.make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.CarrSoln\x12\x0c\n\x04ttff\x18\x0e \x01(\r\x12\x0c\n\x04msss\x18\x0f \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.ublox_ubx_msgs.msg.ubx_nav_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UBXNAVSTATUS']._serialized_start=489
  _globals['_UBXNAVSTATUS']._serialized_end=1104
# @@protoc_insertion_point(module_scope)
