# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/rolling/marti_nav_msgs/msg/grid_map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from make87_messages_ros2.rolling.geometry_msgs.msg import point_pb2 as make87__messages__ros2_dot_rolling_dot_geometry__msgs_dot_msg_dot_point__pb2
from make87_messages_ros2.rolling.sensor_msgs.msg import image_pb2 as make87__messages__ros2_dot_rolling_dot_sensor__msgs_dot_msg_dot_image__pb2
from make87_messages_ros2.rolling.std_msgs.msg import header_pb2 as make87__messages__ros2_dot_rolling_dot_std__msgs_dot_msg_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>make87_messages_ros2/rolling/marti_nav_msgs/msg/grid_map.proto\x12/make87_messages_ros2.rolling.marti_nav_msgs.msg\x1a:make87_messages_ros2/rolling/geometry_msgs/msg/point.proto\x1a\x38make87_messages_ros2/rolling/sensor_msgs/msg/image.proto\x1a\x36make87_messages_ros2/rolling/std_msgs/msg/header.proto\"\xd2\x03\n\x07GridMap\x12\x41\n\x06header\x18\x01 \x01(\x0b\x32\x31.make87_messages_ros2.rolling.std_msgs.msg.Header\x12G\n\x08top_left\x18\x02 \x01(\x0b\x32\x35.make87_messages_ros2.rolling.geometry_msgs.msg.Point\x12H\n\ttop_right\x18\x03 \x01(\x0b\x32\x35.make87_messages_ros2.rolling.geometry_msgs.msg.Point\x12K\n\x0c\x62ottom_right\x18\x04 \x01(\x0b\x32\x35.make87_messages_ros2.rolling.geometry_msgs.msg.Point\x12J\n\x0b\x62ottom_left\x18\x05 \x01(\x0b\x32\x35.make87_messages_ros2.rolling.geometry_msgs.msg.Point\x12\x11\n\tmap_names\x18\x06 \x03(\t\x12\x45\n\x08map_data\x18\x07 \x03(\x0b\x32\x33.make87_messages_ros2.rolling.sensor_msgs.msg.Imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.rolling.marti_nav_msgs.msg.grid_map_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GRIDMAP']._serialized_start=290
  _globals['_GRIDMAP']._serialized_end=756
# @@protoc_insertion_point(module_scope)
