import gradio as gr
from .research import from_frequencies as from_frequencies, from_midi_numbers as from_midi_numbers, from_notes as from_notes

def create_basic_template() -> gr.Blocks: ...
def create_tts_template() -> gr.Blocks: ...
def create_midi_generation_template() -> gr.Blocks: ...
def create_audio_analysis_template() -> gr.Blocks: ...
def create_paper_figure_template() -> gr.Blocks: ...
def create_all_templates() -> gr.Blocks: ...
