# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing_extensions import Literal, TypeAlias

__all__ = ["ResourceType"]

ResourceType: TypeAlias = Literal[
    "RESOURCE_TYPE_UNSPECIFIED",
    "RESOURCE_TYPE_ENVIRONMENT",
    "RESOURCE_TYPE_RUNNER",
    "RESOURCE_TYPE_PROJECT",
    "RESOURCE_TYPE_TASK",
    "RESOURCE_TYPE_TASK_EXECUTION",
    "RESOURCE_TYPE_SERVICE",
    "RESOURCE_TYPE_ORGANIZATION",
    "RESOURCE_TYPE_USER",
    "RESOURCE_TYPE_ENVIRONMENT_CLASS",
    "RESOURCE_TYPE_RUNNER_SCM_INTEGRATION",
    "RESOURCE_TYPE_HOST_AUTHENTICATION_TOKEN",
    "RESOURCE_TYPE_GROUP",
    "RESOURCE_TYPE_PERSONAL_ACCESS_TOKEN",
    "RESOURCE_TYPE_USER_PREFERENCE",
    "RESOURCE_TYPE_SERVICE_ACCOUNT",
    "RESOURCE_TYPE_SECRET",
    "RESOURCE_TYPE_SSO_CONFIG",
    "RESOURCE_TYPE_DOMAIN_VERIFICATION",
    "RESOURCE_TYPE_AGENT_EXECUTION",
    "RESOURCE_TYPE_RUNNER_LLM_INTEGRATION",
    "RESOURCE_TYPE_AGENT",
    "RESOURCE_TYPE_ENVIRONMENT_SESSION",
    "RESOURCE_TYPE_USER_SECRET",
    "RESOURCE_TYPE_ORGANIZATION_POLICY",
]
