# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: make87_messages_ros2/jazzy/topic_tools_interfaces/srv/mux_delete.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFmake87_messages_ros2/jazzy/topic_tools_interfaces/srv/mux_delete.proto\x12\x35make87_messages_ros2.jazzy.topic_tools_interfaces.srv\"!\n\x10MuxDeleteRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"$\n\x11MuxDeleteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'make87_messages_ros2.jazzy.topic_tools_interfaces.srv.mux_delete_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MUXDELETEREQUEST']._serialized_start=129
  _globals['_MUXDELETEREQUEST']._serialized_end=162
  _globals['_MUXDELETERESPONSE']._serialized_start=164
  _globals['_MUXDELETERESPONSE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
