#define SAMTOOLS_CC "clang"
#define SAMTOOLS_CPPFLAGS "-I/Users/runner/work/pysam/pysam/pysam -I/Users/runner/work/pysam/pysam/htslib -I/Users/runner/work/pysam/pysam/samtools -I/Users/runner/work/pysam/pysam/samtools/lz4 -I/Users/runner/work/pysam/pysam/bcftools -I/Users/runner/work/pysam/pysam -DBUILDING_WHEEL"
#define SAMTOOLS_CFLAGS "-fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall   -g -arch x86_64  -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement"
#define SAMTOOLS_LDFLAGS "  -g -arch x86_64 -L/Users/runner/work/pysam/pysam/pysam -L/Users/runner/work/pysam/pysam -Lbuild/lib.macosx-10.9-x86_64-cpython-312/pysam -Lbuild/lib.macosx-10.9-x86_64-cpython-312/pysam -dynamiclib -rpath @loader_path -Wl,-headerpad_max_install_names -Wl,-install_name,@rpath/libcsamtools.cpython-312-darwin.so -Wl,-x"
#define SAMTOOLS_LIBS "-lz -llzma -lbz2 -lz -lcurl -lchtslib.cpython-312-darwin"
#define SAMTOOLS_HTSDIR "(unused)"
#define SAMTOOLS_CURSES_LIB "(unused)"
